### PR TITLE
[gps] add support for UBX PVT message

### PR DESCRIPTION
**Pull request by gautierhattenberger**
PVT is a useful compact and complete message available since Ublox 8. It can eventually replace all other messages for fixedwing, and need extra lla to ecef for rotorcraft.

I don't have GPS module to test it right now, so any help here is welcome :)

### CODE REVIEW

**Comment by fvantienen** [comment]
Nice I can test later! I have also added this in another branch after some rewrite of stuff and will compare.

**Comment by fvantienen** [comment]
On a similar note the log file conversion `sd2log` also creates incorrect dates somehow. Could this also be caused by the GPS rollover bug?

**Comment by gautierhattenberger** [comment]
Not sure, but it could be. Did you check that you have a valid GPS message in the log and what is the value of the `week` field ?

**Comment by fvantienen** [comment]
`41.6560 14 GPS 0 16602173 27 0 -17000 0 0 0 378282750 31 0`

Found the problem, I already implemented the `PVT` message but did not calculate the week, this is why it is `0`. Your implementation should fix the problem. Since `NAV-SOL` was removed there was no message receiving the `week`.

**Comment by fvantienen** [comment]
This is what I had laying around: https://github.com/paparazzi/paparazzi/commit/cb196ca331b13b4369cc7a969c67ee36a72ebbad
It works and flew with it, but I think we should combine these.

**Comment by gautierhattenberger** [comment]
I agree, but not sure if it is better to do it in one step or not

**Comment by fvantienen** [comment]
On another note: FBW builds with GPS fail because I think `gps.c` isn't compiled with it which is now needed for the week calculation.

**Comment by gautierhattenberger** [comment]
yes I just saw that
how are you suppose to use the `gps_ubx` part without the `gps` part ?

**Comment by fvantienen** [comment]
The interMCU does: `AbiBindMsgGPS(IMCU_GPS_ID, &gps_ev, gps_cb);` So it will just forward whatever GPS as secondary GPS.

**Comment by gautierhattenberger** [comment]
is it really a problem to compile gps.c in FBW part ? If it does, I guess we'll need to make gps_common lib for all the small helper functions

**Comment by fvantienen** [comment]
I don't think it will be a problem, so you can test if it works.

**Comment by gautierhattenberger** [comment]
I'm bringing some of your modifications in this pull request.
I didn't do the part about RTCM yet. @fvantienen  Do you think this is something you would need in this PR ?

**Comment by fvantienen** [comment]
I don't need that for now :) Thanks a lot, this seems great!

**Pull request merged**
