### PR TITLE
[rpm-control] throttle curves with rpm control

### PR DESCRIPTION
**Pull request by dewagter**

### CODE REVIEW

**Comment by flixr** [comment]
duplicate of #1832 ?

**Comment by podhrmic** [comment]
in general it would be nice to have more comments in the `throttle_curve` module, including some examples...

**Comment by dewagter** [comment]
- [ ] All airframes files that use this need to be updated
 - [ ] No airframe in conf_tests.xml
 - [ ] Add descriptions to the modules on what exactly they do and how they should be used
 - [ ] The added rpm_control.xml file seems superfluous...
 - [ ] Code style
 - [ ] Also why change the signature of throttle_curve_run? Now you don't pass autopilot_motors_on as parameter anymore but instead take the global var directly... but add ap_mode as parameter instead of using the global var in that case

**Comment by flixr** [comment]
any updates here?

**Comment by podhrmic** [comment]
@dewagter any updates here?

**Comment by OpenUAS** [comment]
Work on this re-started by @fvantienen

**Pull request merged**
