### PR TITLE
Uavcan actuators restyle and telemetry

### PR DESCRIPTION
**Pull request by fvantienen**
- Restyled the code for the actuators
- Added and tested ESC telemetry (Needs to be properly fixed later)
- Fixed performance issues for transmitting after reconnect

Sorry fo this update, but you merged while I was in the middle of testing and updating.

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
Sorry, I thought that the commit was just fixing the config file conflict and that it was fine to merge. Feel free to merge if it is ready.

**Review by gautierhattenberger — DISMISSED** [review]

**Comment by fvantienen** [comment]
Ok I changed some small styling issue, is fine to be merged now

**Review by gautierhattenberger — APPROVED** [review]

**Comment by gautierhattenberger** [comment]
@fvantienen It seems that the nps target for neddrone is failing because the uavcan module is not compiled for this target. Is it an error ?

**Comment by fvantienen** [comment]
This is still to be fixed, working on it. Not 100% sure how to fix it properly if I wanna stub the uavcan module or only the actuators.
What do you think is best to do?

**Pull request merged**
