### PR TITLE
Fixed config course

### PR DESCRIPTION
**Pull request by rmeertens**
One less failing airframe. Will now look at the others.

### CODE REVIEW

**Comment by flixr** [comment]
not fixed yet...
Just run `CONF_XML=conf/airframes/TUDELFT/tudelft_course2016_conf.xml prove tests/aircrafts/`

**Comment by rmeertens** [comment]
Mmm, strange. Seems to be caused by the NPS target which does not see the variables of orange avoider in the flightplan.... Any idea what could have caused this?

**Comment by flixr** [comment]
The orange avoider module is currently only for AP target (until the computer vision stuff is implemented/fixed for NPS)...

**Comment by flixr** [comment]
so unless we can get the compute rvision stuff fixed for NPS target soon, I would suggest to remove/comment the nps target for that airframe (as you can't use it anyway)

**Comment by rmeertens** [comment]
This should work, right?

**Comment by flixr** [comment]
probably, you can test it with the command I posted before...

**Comment by rmeertens** [comment]
That command works ;) Now also removed the warnings.

**Comment by rmeertens** [comment]
Also removed the failing NPS target of TUDELFT.

**Pull request merged**
