### PR TITLE
Optitrack fixes

### PR DESCRIPTION
**Pull request by kevindehecker**
These are the changes I needed to make, to fly the ARDrone2 in the Cyberzoo, using the optitrack system for altitude and yaw estimation. Without it, several bugs such as #977 appear on quasi-regular basis.

Basically, this disables the baro+magneto (sonar was already disabled) and fixes some code that kind of ignored those settings or caused problems for it.

### CODE REVIEW

**Comment by flixr** [comment]
Thx. The last two commits look good to me.
The `#if USE_BARO_BOARD` check in ins_int.c is not what we want to use here however...
E.g. you might have an external baro connected.
However I think that we can simply always propagate the vff and skip the check for `ins_int.baro_initialized` completely.
@gautierhattenberger do you see any reason to only propagate the filter if the baro is not yet initialized?

**Comment by gautierhattenberger** [comment]
I think the issue is that if the baro takes some time to be initialized (with was the case for the analog baro of Booz boards, so maybe not relevant anymore...), the ins will diverge during this time.
It is probably not a really big issue, especially on recent boards with digital barometers.

**Comment by flixr** [comment]
It will not diverge if you have gps or sonar measurements during that time.
I think a better solution than only checking if the baro is initialized is to simply have some sort of counter that resets with every update and if you don't get any updates it times out and stops the propagation.

**Comment by flixr** [comment]
I merged everything except the check "propagation fix" via `#if USE_BARO_BOARD`:
ecd3b1a75f0c19860ccbc5d011626f107d7a2a30
20f8670ba9ae4efe10a4e7e1565a50079e033f90
c2a4b2b3ed2c9178678ffd0ce721be72211ed40e

**Comment by flixr** [comment]
finally closed with #1241

**Pull request closed without merging**
