### PR TITLE
first step towards camera interface

### PR DESCRIPTION
**Pull request by rmeertens**
Hey everybody, 

Creating this pull request to get feedback from you before going further. As this is the first time I'm creating a C++ interface to be used by C I am having a lot of doubts about how to proceed. 

In the end we want to have a camera interface which every camera implements in a c++ class. Next to this we still need a binding with c... so we will call a function mt9f_camera_resize(w,h), which then takes the camera object and calls resize on that one?

As I don't have that much time to spend on this: what would the fastest way be to get a simple working program?

### CODE REVIEW

**Comment by rmeertens** [comment]
Ok. Got some more code. Camera is now working with the C++ interface. @fvantienen @flixr could use some initial feedback on the direction i'm now going in. 

@fvantienen you mentioned that setting these parameters can't be done whenever I want. Can you indicate how and when we want to adjust them?

**Comment by EwoudSmeur** [comment]
Is this still relevant, as @fvantienen is working on a vision framework? Should we close this?

**Comment by flixr** [comment]
@rmeertens is this still relevant or can we close it?

**Comment by rmeertens** [comment]
As @fvantienen started on the vision framework again (and I'm not building it anymore) I think it's up to him...

**Comment by rmeertens** [comment]
But knowing Freek I can probably close it now ;)

**Pull request closed without merging**
