### PR TITLE
Rtk moving baseline and extended gpschannels

### PR DESCRIPTION
**Pull request by djchris261**
Added 4072 and 1230 messages required for moving baseline and extended number of channels for GPS.

Minor bugfix in case msg_len = 0 (rtcm3.h - line 353) 

Testing performed for both moving baseline and Survey In case. DGPS obtained successfully.

### CODE REVIEW

**Comment by OpenUAS** [comment]
Could use a squash... anyhow we will discuss it in a 1on1 tomorrow.

**Comment by djchris261** [comment]
Squashed and additional fixes. New PR will follow.

**Comment by gautierhattenberger** [comment]
@djchris261 doing a push in the same branch, event with `--force` will update the PR, no need to close and open a new one. For the next time.

**Comment by djchris261** [comment]
@gautierhattenberger I tried to still reopen the PR today but ran into different git errors. Apologies for this. Just opened a new PR.

**Pull request closed without merging**
