### PR TITLE
INDI - flightplan attitude fix

### PR DESCRIPTION
**Pull request by dewagter**
Setting attitude from the flightplan was spinning when the heading is not perfectly north.

@EwoudSmeur: is this OK?

### CODE REVIEW

**Comment by EwoudSmeur** [comment]
that function has as a comment: // only a plug for now... doesn't apply roll/pitch wrt. current yaw angle
in guidance_h.c the function is only called if you set the attitude from the flight plan, would you want roll and pitch to be applied to the current or the supposed-to-be yaw angle?

this was changed in february for quat_int with https://github.com/paparazzi/paparazzi/commit/8634b728ae6fff28acd89e14394b3906180f74b5

We can adopt this change, but I don't see how this would have anything to do with spinning

**Comment by dewagter** [comment]
I did not investigate _why_ but unless ```psi=0``` is commanded, the quad would apply a mix of bank and pitch instead of pure pitch commands. With the spinning I mean the direction (mix of pitch and roll) in which the pitch command was executed to would vary in time when using ```quat_from_rpy_cmd_i```. (like if the heading command was integrated)

So if you know no objection I will apply this pull request because it solves the setting of attitude from the flightplan for non zero headings in INDI.

**Comment by EwoudSmeur** [comment]
ok

**Comment by OpenUAS** [comment]
THX ! (= less repairing...)

**Pull request merged**
