### PR TITLE
In phases add all OUAS flyable airframes

### PR DESCRIPTION
**Pull request by OpenUAS**
Phases:
----

The first batch of used aircraft for PPRZ validation fun. This way it is way easier to testfly PPRZ master branch and merge fixes found in e.g. cherrypicked PR's

Based on pure master branch. A new branch with fixes already made during airframe testing will be add shortly. Note that not all airframes are tuned to fly well, in another PR, likely spring when it is not freezingly cold ;)

All airframes tested locally on compilability via:

```
cd ~/paparazzi
PAPARAZZI_SRC=$PWD PAPARAZZI_HOME=$PWD J=AUTO CONF_XML=conf/userconf/OPENUAS/openuas_conf.xml HIDE_WARNINGS=1 prove tests/aircrafts
```

Now lets see if the Paparazzi CI server can handle it... :crossed_fingers: 

Local Result:
--------------------------------------
tests/aircrafts/01_compile_all_aircrafts.t .. 1/71 # compiling AIRCRAFT: [ARDrone_2] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 2/71 # compiling AIRCRAFT: [ARDrone_2] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 3/71 # compiling AIRCRAFT: [Bebop] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 4/71 # compiling AIRCRAFT: [Bebop] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 5/71 # compiling AIRCRAFT: [Bebop_2_Black] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 6/71 # compiling AIRCRAFT: [Bebop_2_Black] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 7/71 # compiling AIRCRAFT: [Bebop_2_White] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 8/71 # compiling AIRCRAFT: [Bebop_2_White] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 9/71 # compiling AIRCRAFT: [Bebopeye] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 10/71 # compiling AIRCRAFT: [Bebopeye] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 11/71 # compiling AIRCRAFT: [Crazyfly_2_1] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 12/71 # compiling AIRCRAFT: [Crazyfly_2_1] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 13/71 # compiling AIRCRAFT: [Disco_A] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 14/71 # compiling AIRCRAFT: [Disco_A] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 15/71 # compiling AIRCRAFT: [Disco_A] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 16/71 # compiling AIRCRAFT: [Disco_B] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 17/71 # compiling AIRCRAFT: [Disco_B] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 18/71 # compiling AIRCRAFT: [Disco_B] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 19/71 # compiling AIRCRAFT: [Disco_C] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 20/71 # compiling AIRCRAFT: [Disco_C] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 21/71 # compiling AIRCRAFT: [Disco_C] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 22/71 # compiling AIRCRAFT: [Disco_D] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 23/71 # compiling AIRCRAFT: [Disco_D] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 24/71 # compiling AIRCRAFT: [Disco_D] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 25/71 # compiling AIRCRAFT: [EFlite_T28] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 26/71 # compiling AIRCRAFT: [EFlite_T28] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 27/71 # compiling AIRCRAFT: [EFlite_T28] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 28/71 # compiling AIRCRAFT: [Flexo] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 29/71 # compiling AIRCRAFT: [Flexo] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 30/71 # compiling AIRCRAFT: [Flexo] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 31/71 # compiling AIRCRAFT: [G2] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 32/71 # compiling AIRCRAFT: [G2] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 33/71 # compiling AIRCRAFT: [Goblin] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 34/71 # compiling AIRCRAFT: [Goblin] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 35/71 # compiling AIRCRAFT: [Iris_Plus] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 36/71 # compiling AIRCRAFT: [Iris_Plus] TARGET: [fbw]
tests/aircrafts/01_compile_all_aircrafts.t .. 37/71 # compiling AIRCRAFT: [Iris_Plus] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 38/71 # compiling AIRCRAFT: [Itsy_Bitsy] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 39/71 # compiling AIRCRAFT: [Itsy_Bitsy] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 40/71 # compiling AIRCRAFT: [Mini_Spirit] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 41/71 # compiling AIRCRAFT: [Mini_Spirit] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 42/71 # compiling AIRCRAFT: [Mini_Spirit] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 43/71 # compiling AIRCRAFT: [Minimag] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 44/71 # compiling AIRCRAFT: [Minimag] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 45/71 # compiling AIRCRAFT: [Minimag] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 46/71 # compiling AIRCRAFT: [Moksha] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 47/71 # compiling AIRCRAFT: [Quadshot_W_Negative] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 48/71 # compiling AIRCRAFT: [Quadshot_W_Negative] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 49/71 # compiling AIRCRAFT: [Quadshot_W_Positive] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 50/71 # compiling AIRCRAFT: [Quadshot_W_Positive] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 51/71 # compiling AIRCRAFT: [Sumo_II] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 52/71 # compiling AIRCRAFT: [Sumo_II] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 53/71 # compiling AIRCRAFT: [Sumo_II] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 54/71 # compiling AIRCRAFT: [Taxi_III] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 55/71 # compiling AIRCRAFT: [Taxi_III] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 56/71 # compiling AIRCRAFT: [Tinyhawk_II] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 57/71 # compiling AIRCRAFT: [Trashcan] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 58/71 # compiling AIRCRAFT: [Trashcan_voir] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 59/71 # compiling AIRCRAFT: [Twinstar_ND] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 60/71 # compiling AIRCRAFT: [Twinstar_ND] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 61/71 # compiling AIRCRAFT: [Twinstar_ND] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 62/71 # compiling AIRCRAFT: [UMX_Sbach_342] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 63/71 # compiling AIRCRAFT: [UMX_Sbach_342] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 64/71 # compiling AIRCRAFT: [UMX_Sbach_342] TARGET: [test_actuators_pwm_sin]
tests/aircrafts/01_compile_all_aircrafts.t .. 65/71 # compiling AIRCRAFT: [Vivify] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 66/71 # compiling AIRCRAFT: [Vivify] TARGET: [fbw]
tests/aircrafts/01_compile_all_aircrafts.t .. 67/71 # compiling AIRCRAFT: [Vivify] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 68/71 # compiling AIRCRAFT: [Vivify] TARGET: [tunnel]
tests/aircrafts/01_compile_all_aircrafts.t .. 69/71 # compiling AIRCRAFT: [XVert] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. ok     
All tests successful.
Files=1, Tests=71, 375 wallclock secs ( 0.03 usr  0.01 sys + 1836.92 cusr 208.77 csys = 2045.73 CPU)
Result: PASS

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
It will most likely be an issue for CI servers. The Travis CI is currently blocked for Paparazzi because we have consumed all our "free" credits. And the Semaphore night build that is testing all confs is already so long that there is a good chance it will stop due to timeout.
So I'm fine in updating the airframe file, especially if they have been tested locally, but adding them to a conf XML is probably not the best.
As a side note, we are working on a better way to test the code than compiling hundreds of targets with 90% the same code.

**Comment by OpenUAS** [comment]
"but adding them to a conf XML is probably not the best." > Yes, note that they are all real aircraft flyable, not for testing the build. 

I do **not propose** to add the aircraft to the default test :). But CI starts testing it automatically as soon as we make a Pull request.

**Comment by gautierhattenberger** [comment]
I'm happy with the airframe files themselves, it is just that maybe we should not have all of them in  conf/userconf/OPENUAS/openuas_conf.xml

**Comment by OpenUAS** [comment]
OK, I can remove all except one, and add a symlink to a local conf.xml . Thus will then re-name it e.g. "openuas_all_ac.xml", so without the "conf" in the naming this way it will not be used in CI build but I can still update it and add to master and switch to it by manually adding the symlink on dev PC's and two fieldlaptops. 

Q: would that be acceptable?

 Main reason is Travis CI overload right?

JFYI: Since I build on my own travis also as soon as I push I know already if a build fails before a PR

**Comment by gautierhattenberger** [comment]
The night build (on all confs) runs on Semaphore, but since Travis is already stuck, I don't want to take the risk to overload Semaphore as well.
We can give a try with your solution and see if it works like this.

**Comment by OpenUAS** [comment]
OK, will make new PR,  BTW I'm afraid this is the reality for Travis CI https://medium.com/@dirk.avery/r-i-p-travis-ci-347753c73775

**Comment by OpenUAS** [comment]
A personal userconf is never used in Travis CI only the airframes in ~/paparazzi/conf/conf_tests.xml  so removing them from personal conf should make no differen to anything. But maybe for semaphore ci build?.. will investigate and report back...

**Comment by OpenUAS** [comment]
PAPARAZZI_SRC=$PWD PAPARAZZI_HOME=$PWD J=AUTO CONF_XML=conf/userconf/OPENUAS/openuas_conf.xml HIDE_WARNINGS=1 prove tests/aircrafts

tests/aircrafts/01_compile_all_aircrafts.t .. 1/5 # compiling AIRCRAFT: [Minimag] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 2/5 # compiling AIRCRAFT: [Minimag] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 3/5 # compiling AIRCRAFT: [Minimag] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. ok   
All tests successful.
Files=1, Tests=5, 14 wallclock secs ( 0.02 usr  0.00 sys + 77.86 cusr  8.35 csys = 86.23 CPU)
Result: PASS

and on request o the special xml

PAPARAZZI_SRC=$PWD PAPARAZZI_HOME=$PWD J=AUTO CONF_XML=conf/userconf/OPENUAS/openuas_all_ac.xml HIDE_WARNINGS=1 prove tests/aircrafts
tests/aircrafts/01_compile_all_aircrafts.t .. 1/71 # compiling AIRCRAFT: [ARDrone_2] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 2/71 # compiling AIRCRAFT: [ARDrone_2] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 3/71 # compiling AIRCRAFT: [Bebop] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 4/71 # compiling AIRCRAFT: [Bebop] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 5/71 # compiling AIRCRAFT: [Bebop_2_Black] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 6/71 # compiling AIRCRAFT: [Bebop_2_Black] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 7/71 # compiling AIRCRAFT: [Bebop_2_White] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 8/71 # compiling AIRCRAFT: [Bebop_2_White] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 9/71 # compiling AIRCRAFT: [Bebopeye] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 10/71 # compiling AIRCRAFT: [Bebopeye] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 11/71 # compiling AIRCRAFT: [Crazyfly_2_1] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 12/71 # compiling AIRCRAFT: [Crazyfly_2_1] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 13/71 # compiling AIRCRAFT: [Disco_A] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 14/71 # compiling AIRCRAFT: [Disco_A] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 15/71 # compiling AIRCRAFT: [Disco_A] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 16/71 # compiling AIRCRAFT: [Disco_B] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 17/71 # compiling AIRCRAFT: [Disco_B] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 18/71 # compiling AIRCRAFT: [Disco_B] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 19/71 # compiling AIRCRAFT: [Disco_C] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 20/71 # compiling AIRCRAFT: [Disco_C] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 21/71 # compiling AIRCRAFT: [Disco_C] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 22/71 # compiling AIRCRAFT: [Disco_D] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 23/71 # compiling AIRCRAFT: [Disco_D] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 24/71 # compiling AIRCRAFT: [Disco_D] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 25/71 # compiling AIRCRAFT: [EFlite_T28] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 26/71 # compiling AIRCRAFT: [EFlite_T28] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 27/71 # compiling AIRCRAFT: [EFlite_T28] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 28/71 # compiling AIRCRAFT: [Flexo] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 29/71 # compiling AIRCRAFT: [Flexo] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 30/71 # compiling AIRCRAFT: [Flexo] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 31/71 # compiling AIRCRAFT: [G2] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 32/71 # compiling AIRCRAFT: [G2] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 33/71 # compiling AIRCRAFT: [Goblin] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 34/71 # compiling AIRCRAFT: [Goblin] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 35/71 # compiling AIRCRAFT: [Iris_Plus] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 36/71 # compiling AIRCRAFT: [Iris_Plus] TARGET: [fbw]
tests/aircrafts/01_compile_all_aircrafts.t .. 37/71 # compiling AIRCRAFT: [Iris_Plus] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 38/71 # compiling AIRCRAFT: [Itsy_Bitsy] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 39/71 # compiling AIRCRAFT: [Itsy_Bitsy] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 40/71 # compiling AIRCRAFT: [Mini_Spirit] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 41/71 # compiling AIRCRAFT: [Mini_Spirit] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 42/71 # compiling AIRCRAFT: [Mini_Spirit] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 43/71 # compiling AIRCRAFT: [Minimag] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 44/71 # compiling AIRCRAFT: [Minimag] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 45/71 # compiling AIRCRAFT: [Minimag] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 46/71 # compiling AIRCRAFT: [Moksha] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 47/71 # compiling AIRCRAFT: [Quadshot_W_Negative] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 48/71 # compiling AIRCRAFT: [Quadshot_W_Negative] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 49/71 # compiling AIRCRAFT: [Quadshot_W_Positive] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 50/71 # compiling AIRCRAFT: [Quadshot_W_Positive] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 51/71 # compiling AIRCRAFT: [Sumo_II] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 52/71 # compiling AIRCRAFT: [Sumo_II] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 53/71 # compiling AIRCRAFT: [Sumo_II] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 54/71 # compiling AIRCRAFT: [Taxi_III] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 55/71 # compiling AIRCRAFT: [Taxi_III] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 56/71 # compiling AIRCRAFT: [Tinyhawk_II] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 57/71 # compiling AIRCRAFT: [Trashcan] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 58/71 # compiling AIRCRAFT: [Trashcan_voir] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 59/71 # compiling AIRCRAFT: [Twinstar_ND] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 60/71 # compiling AIRCRAFT: [Twinstar_ND] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 61/71 # compiling AIRCRAFT: [Twinstar_ND] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 62/71 # compiling AIRCRAFT: [UMX_Sbach_342] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 63/71 # compiling AIRCRAFT: [UMX_Sbach_342] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 64/71 # compiling AIRCRAFT: [UMX_Sbach_342] TARGET: [test_actuators_pwm_sin]
tests/aircrafts/01_compile_all_aircrafts.t .. 65/71 # compiling AIRCRAFT: [Vivify] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 66/71 # compiling AIRCRAFT: [Vivify] TARGET: [fbw]
tests/aircrafts/01_compile_all_aircrafts.t .. 67/71 # compiling AIRCRAFT: [Vivify] TARGET: [sim]
tests/aircrafts/01_compile_all_aircrafts.t .. 68/71 # compiling AIRCRAFT: [Vivify] TARGET: [tunnel]
tests/aircrafts/01_compile_all_aircrafts.t .. 69/71 # compiling AIRCRAFT: [XVert] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. ok     
All tests successful.
Files=1, Tests=71, 347 wallclock secs ( 0.03 usr  0.00 sys + 1821.10 cusr 197.74 csys = 2018.87 CPU)
Result: PASS

**Comment by OpenUAS** [comment]
Not that also this original PR also should have no impact of build on https://semaphoreci.com/paparazziuav/paparazzi
But just in case ,changed it anyhow as requested.

**Comment by OpenUAS** [comment]
screenshot_from_semaphoreci

**Comment by OpenUAS** [comment]
I rather would have had the first PR honored, but I'll make a new request then is ln -s whatever.xml conf.xml really start to annoy enough :smirk:

**Pull request merged**
