### PR TITLE
[opencv] FIX gzeof linking error

### PR DESCRIPTION
**Pull request by dewagter**
* FIX gzeof linking error

Order of libraries is crucial. See https://github.com/paparazzi/paparazzi/issues/2673

### CODE REVIEW

**Comment by dewagter** [comment]
Fixed with https://github.com/paparazzi/paparazzi/commit/b1d38486fdecd28d8c8d83e4cc2f47a2d95605ce

**Comment by dewagter** [comment]
The previous fix (b1d3848) does not solve the problem for me.

**Comment by gautierhattenberger** [comment]
@dewagter It seems in the correct order for me, except that there are multiple loading of libs from different modules:
```
 -static -lrt -L/home/gautier/dev/paparazzi/sw/ext/opencv_bebop/install_arm/lib -lopencv_world -L/home/gautier/dev/paparazzi/sw/ext/opencv_bebop/install_arm/share/OpenCV/3rdparty/lib -llibprotobuf -llibjpeg-turbo -llibpng -llibtiff -lzlib -lquirc -ltegra_hal -ldl -lm -lpthread -lrt -lrt -static-libgcc -lm -pthread
```
Each individual module however loads them in the right order. Which flags are making problems ?

**Comment by dewagter** [comment]
Correction: I wrongly assumed the fix was already in master. #2684 fixes the problem.

**Pull request closed without merging**
