### PR TITLE
Add a Codacy badge to README.md

### PR DESCRIPTION
**Pull request by codacy-badger**

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
closed with 0a6d735804308d9ba319fd431b7d2486ba2ec77d

**Comment by podhrmic** [comment]
@gautierhattenberger nothing against adding another code quality metrics, but this PR seems to be at least partially automated (check @codacy-badger 's list of PRs). So I don't really like the approach, it feels like spam.

**Comment by gautierhattenberger** [comment]
they have a 'add badge' button, but I didn't expect this to make an automated PR. Add I override it by hand in the end. This is just for trial, if it as not useful or too annoying I will remove it. I am getting some report emails on PR, do you have it too or is it only me ?

**Comment by podhrmic** [comment]
I haven't received any emails. Sounds good, lets see how useful it will be.

**Pull request closed without merging**
