### PR TITLE
Linux video update

### PR DESCRIPTION
**Pull request by dewagter**
- [x] opticflow
 - [x] viewvideo / videorecord
 - [x] last mutex problem: possible lost image
 - [ ] opticflow use new functions
 - [x] image_nc_send use new functions
 - [ ] fix more settings for the viewvideo module to be changed at runtime
 - [ ] fix bebop CMOS configuration failing sometimes

This also removes some of #1079 which was inside the vision framework.

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
the file image_nc_send also need to be updated to use the new API, it should be very similar to viewvideo.c

**Comment by dewagter** [comment]
any objection to merge this?

**Comment by flixr** [comment]
Is your third point "last mutex problem: possible lost image" fixed/done?
Without looking at the code I have no idea what the intended changes are, would have been nice to write that in the pull request ;-)

**Comment by fvantienen** [comment]
It was in there. But it is during the image free, you set the index to 255 (which means none dequeued, define should be nice) if the current index is the only one dequeued. Problem is that during this check the image thread can change this idx, and you will lose this buffer.

**Comment by flixr** [comment]
@dewagter your call... if you want to merge it with this last point unresolved, go ahead...

**Comment by fvantienen** [comment]
I will fix it tomorrow with a simple extra mutex lock. Was searching for a nicer solution, but couldn't find it.
But since this lock can only happen at very little occasions I think it shouldn't be a problem to just use another mutex.

**Comment by fvantienen** [comment]
Maybe we should also rename the different modules?
We now have names like "cv_opticflow.xml", "video_rtp_stream.xml" and "image_nc_send.xml". Maybe start everything with cv_?

**Comment by fvantienen** [comment]
Currently the CMOS configuration of the Bebop sometimes fails. Don't know how to fix it yet, but hope to have more information soon.
Next to that I changed a lot of the jpeg/rtp function names to avoid double function names.

**Comment by OpenUAS** [comment]
while cv_ is a fine name change from our programmers perspective, however out of experience with students and others coding, a lot of them will confuse it thas to do with Open CV, I would propose something else if only I had some beter ideas anyhow, e.g. iavh_ (**i**mage **a**nd **v**ideo **h**andling) , whatever.... at least something distinctive even fvt_ , cdw_ ;) then others can make up the real meaning of the characters

**Comment by fvantienen** [comment]
I removed the nc_send_image module, because it was 99% the same as the viewvideo module. Instead I made a setting "VIEWVIDEO_USE_NC" that does the same as the nc_send_image module.

**Comment by flixr** [comment]
Can you please add the VIEWVIDEO_USE_NC flag to the description in the module xml?
Maybe calling it VIEWVIDEO_USE_NETCAT would also be a bit more clear?

**Comment by fvantienen** [comment]
I changed the define, if you got other comments please tell them ;) It's still a WIP, but I want to merge this  as soon as possible, because this will help a lot of people in our computer vision course.

**Comment by flixr** [comment]
I think we can merge it after #1117 is (good to be) merged...

**Comment by flixr** [comment]
Actually I don't think it makes sense to use udp_periph in `rtp_send` or any of these modules that don't actually use any of the UART like periph functions...

**Comment by dewagter** [comment]
cv was for computer vision. for me streaming video does not need to be
called computer vision but I would not mind a lot either.

-Christophe

**Pull request merged**
