### PR TITLE
[slam_dunk] communication

### PR DESCRIPTION
**Pull request by dewagter**
landing guidance and target searching using S.L.A.M.Dunk

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
Shouldn't we make more reference to the official device name (Slam_Dunk) at least in the documentation ?

**Comment by flixr** [comment]
any updates here?

**Comment by flixr** [comment]
@dewagter ping...

**Comment by dewagter** [comment]
Dear @flixr, it has not been possible yet to make delftacopter fly with
master. Until then this module is not required. Due to lack of manpower on
the project, I'm OK with closing this pull-request.

-Christophe

**Comment by flixr** [comment]
@dewagter your call

**Comment by podhrmic** [comment]
@flixr wait or close?

**Pull request closed without merging**
