### PR TITLE
global fix of current warnings and errors in CI server

### PR DESCRIPTION
**Pull request by gautierhattenberger**
this should fix most of the warnings and hopefully all the errors in the CI builds

### CODE REVIEW

**Comment by dewagter** [comment]
Looking good to me.
Has some overlap with: https://github.com/paparazzi/paparazzi/pull/2336
We will try to remove more airframes during the next PPRZ-day.

**Comment by gautierhattenberger** [comment]
can I merge this one and close #2336 ? It seems it is only a subset

**Comment by gautierhattenberger** [comment]
builds are too long for travis again....

**Comment by dewagter** [comment]
Yes you can merge this and close #2336

**Comment by gautierhattenberger** [comment]
I had to remove the tudelf conf corresponding to your helicopters since the airframe files are not happy with the heli_mixing stuff. I leave it to you to fix that if needed.

**Comment by dewagter** [comment]
@freek delftacopter breaks the helis

**Pull request merged**
