### PR TITLE
[settings] separated settings files

### PR DESCRIPTION
**Pull request by TobiasMue**
since we have the opportunity to select more than just one setting file in GCS and it is really simple to select/deselect each, there is no need to have everything in one file for every possible configuration
therefor I stated separating those files
next step should be to delete the old files where everything is mixed up
this should make it much easier to keep them up to date and if someone wants to make his own one he can easily look up what is needed or available for each setting block
in addition I found a small typo inane of the files...

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
I completely agree on the principal. The issue is that for people using these settings files (my case), the configuration will not be broken but things will be missing.
I'd like to have more feedbacks from other users/devs.

**Comment by flixr** [comment]
Before the end of the year we will hopefully have "merged" subsystem and module configurations with support for auto loading settings for subsystems like for modules... then it will be solved in a nicer way...
I have no strong opinion in how we handle it until then...

**Comment by TobiasMue** [comment]
maybe we could merge these files anyway and just rename them to something like plane_ctrl_nav.xml or plane_ctrl_energy.xml etc…. this won't brake anything and no one is missing anything and the name should speak for it self. could be a nice transition until self loading really exists.

**Comment by OpenUAS** [comment]
@TobiasMue or other devs, feel free to set to 5.8 release if really needed.

**Comment by dewagter** [comment]
- changing splitting the settings sound fine
 - module-settings are better
 - in case settings are split, this requires a user change then combine with a release and mailinglist item.
 - since there are many special changes requiring user action like this, we could argue that the next release is 6.0

**Comment by podhrmic** [comment]
Is this still a thing? IMHO the functionality already exists in the master...?

**Comment by flixr** [comment]
Closing, as most of these settings will be moved into the respective modules soon anyway....

**Pull request closed without merging**
