### PR TITLE
replace bool_t with C99 bool from stdbool.h

### PR DESCRIPTION
**Pull request by flixr**
Commonly people use `bool` from `stdbool.h` and this is usually the recommended way.
This requires C99, but we already use that anyway...

This should make integration with some other things easier, e.g.
- chibios, which has it's own `bool_t` typedef
- building python wrappers that map it to a python bool

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
`sed` is your friend

I think it is fine for merging.

**Comment by flixr** [comment]
@dewagter @martinmm @fvantienen @podhrmic @esden 
Do you see any reasons not to merge this and keep the `typedef uint8_t bool_t`?

**Comment by gautierhattenberger** [comment]
Guys, does anyone have comments ? I have some stuff I'd like to rebase on top of this if it is integrated, it would save some conflict merging issues...

**Comment by martinmm** [comment]
Don't see any issue with changing it

**Comment by OpenUAS** [comment]
Really would like to see this indeed

**Pull request merged**
