### PR TITLE
Remove static sectors

### PR DESCRIPTION
**Pull request by Fabien-B**
As suggested in #2677, I propose here to remove static sectors. All sector will be dynamic ones.

### CODE REVIEW

**Review by fvantienen — APPROVED** [review]
I fully agree, this also removes the problem with the correct orientation.

**Comment by gautierhattenberger** [comment]
I also agree, but maybe one little thing: we should keep the DTD unchanged for some time and print a warning with a deprecated message when using `type`. People with personal flight plans should have some time to fix them if needed.

**Comment by Fabien-B** [comment]
I suggest making it an error, so people will take care of the problem before the DTD change.
Running now in `Error: attribute "type" on tag sector is deprecated and must be removed` is better than not paying attention to a warning, and running in a few weeks in a n obscure `DTD error`.

**Comment by fvantienen** [comment]
I agree with the error, this forces people to update their files.

On a side note, shouldn't we list those deprecations somewhere with a specific enddate and a link to the specific code to remove/update. This reminds both the user and maintainers to update/remove this code. So my advice is to do the following:
- Remove all code that is labeled 'deprecated' for more than 1 year or add them to the list
- For new deprecations like this, add them to a list in a file somewhere with a specific enddate

**Comment by Fabien-B** [comment]
Maybe we can use this github action, together with issues for that?
https://github.com/marketplace/actions/due-dates
And we can also set a "deprecation" tag to these issues so people can find them easily.

**Comment by fvantienen** [comment]
For me that seems fine 👍  What do you think @gautierhattenberger ?

**Comment by gautierhattenberger** [comment]
we can give a try until github have a proper "due date" option for pull requests

Here, we have also moved the definition of sectors outside the `NAV_C` part, so you can use that anywhere in the code and don't need the (dangerous) workaround to define NAV_C twice.

**Review by fvantienen — APPROVED** [review]
Seems fine 👍

**Pull request merged**
