### PR TITLE
fix origin altitude ekf2

### PR DESCRIPTION
**Pull request by EwoudSmeur**
HMSL was set to be altitude...

### CODE REVIEW

**Review by fvantienen — APPROVED** [review]

**Comment by gautierhattenberger** [comment]
@EwoudSmeur @fvantienen Are you sure about this ? In the header file `https://github.com/PX4/PX4-ECL/blob/master/EKF/common.h#L67` it says that it should be altitude above MSL in millimeters.

**Comment by EwoudSmeur** [comment]
I'm sure the altitude of my absolute waypoints was off by 40 meters, and the message ins_ref reported the origin at 0m alt, which should be 40m at our flight field. It doesn't make sense to me to write hmsl to an alt value as well.

Perhaps we're not interpreting the ekf2 struct correctly when setting the origin?

**Comment by gautierhattenberger** [comment]
It is not all clear, but I think the problem comes from the initial altitude used as filter's origin.
If you look at https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/ekf2/EKF2.cpp#L1171, the absolute `alt` is the filter z value + the origin, while `alt_ellipsoid` is explicitly computed from `alt`. You can also see in https://github.com/PX4/PX4-Autopilot/blob/main/msg/SensorGps.msg#L10 that `altitude` is the MSL value for them.
If me have an offset in paparazzi, I think it might come from the init value in https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/modules/ins/ins_ekf2.cpp#L525. We are using `NAV_ALT0 + NAV_MSL0` as initial altitude. However `NAV_ALT0` is the alt AMSL, and `NAV_MSL0` is the difference between geoid and ellipsoid. So I think we should initialize with `NAV_ALT0` only and update the filter with `hmsl` like before to be consistent with the filter's "documentation".

**Comment by fvantienen** [comment]
Indeed I think it would be better to change everything to AMSL if the ekf2 expects that. So changing the initialization would be best and also the conversion from ekf2 origin to pprz origin.

**Comment by dewagter** [comment]
Continued in https://github.com/paparazzi/paparazzi/pull/3106

**Pull request merged**
