### PR TITLE
+logging function for natnet2ivy

### PR DESCRIPTION
**Pull request by rmeertens**
added a logging function to see what was sent to the drone.

### CODE REVIEW

**Comment by kirkscheper** [comment]
This removes lots of previous work, can you merge instead of overwriting?

**Comment by rmeertens** [comment]
Mmm, looks like I messed up again. Will do!

**Comment by kirkscheper** [comment]
also this only logs if small messages are not set, can you move the log outside the brackets to log regardless.

**Comment by kirkscheper** [comment]
maybe also give a unique time to each log and have them stored in the var folder and not the paparazzi home folder?

**Pull request closed without merging**
