### PR TITLE
T4 actuators and sensors

### PR DESCRIPTION
**Pull request by dewagter**
@alessandro-mancinelli 
@sunyouh
@OpenUAS 

Several airframes are now relying on this Teensy module to have more actuators and sensors. Where can I find the Teensy code.

### CODE REVIEW

**Comment by alessandro-mancinelli** [comment]
Hi Christophe, the source code for the teensy is available at the following repo: https://github.com/tudelft/Teensy_actuators_PPZ

**Comment by dewagter** [comment]
@dewagter compare with
SHA1 ID: 9df0f6a5e833a5ad6402e3463332956533da557d
branch: tudelft/overactuated_quadplane_ship_landing_single_loop_new_aero_model_merged

**Comment by OpenUAS** [comment]
Note that work is ongoing on this branch also https://github.com/paparazzi/paparazzi/compare/master...tudelft:paparazzi:add_t4_actuators_module  to use ABI messages and have a more integrated solution, as in mixing can be done in Airframer file. Also universiall should work on Sim and Linux as target.

**Comment by dewagter** [comment]
> Note that work is ongoing on this branch also [master...tudelft:paparazzi:add_t4_actuators_module](https://github.com/paparazzi/paparazzi/compare/master...tudelft:paparazzi:add_t4_actuators_module) to use ABI messages and have a more integrated solution, as in mixing can be done in Airframer file. Also universiall should work on Sim and Linux as target.

Let's all continue with your branch.

**Pull request closed without merging**
