### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by gautierhattenberger**
Fix some warnings found by CI servers.

Most of the remaining warnings are coming from invalid confs or flight plans (especially IMAV2015 FP from TUDelft). It would be nice to fix them or remove them.

### CODE REVIEW

**Comment by dewagter** [comment]
Where can I find the list of failing confs?

Added some fixes here: f676d97e39f8c060f22b324bfaf9b5e55f46793e

**Comment by gautierhattenberger** [comment]
It is in semaphore nightly builds: https://semaphoreci.com/paparazziuav/paparazzi/branches/master/builds/35

**Comment by gautierhattenberger** [comment]
Do you think I can already merge this, since it is removing half of the warnings ?
@OpenUAS there is a VivifyMKK airframe in your conf that generates a lot of warnings/error, can you check this file ?

**Comment by dewagter** [comment]
I fixed some of the OpenUAS warnings/errors.

1 big problem remains: the change in access to UART devices requires a
rewrite of digital_cam_uart. Who made this change?

Concerning the merge: I would say certainly!

-Christophe

**Comment by gautierhattenberger** [comment]
I guess I did most of the changes, but if it is broken, I guess it is out of the scope of this pull request. Let's merge it and I let you open an issue for the uart cam driver if needed.

**Pull request merged**
