### PR TITLE
Added support for HooperFly Hexa and Quad frames

### PR DESCRIPTION
**Pull request by hooperfly**
Added two new rotor icon types:
  "hexarotor" - for use by hexacopter frames (uses a hoop for the body)
  "quadrotor" - for use by quadrotor frames (uses a hoop for the body)

Added and tested simulator aircraft definitions:
  * TeensyFly and RacerPEX Hexacopters
  * TeensyFly and RacerPEX Quadcopters

Added and tested airframe configuration definitions:
  * TeensyFly and RacerPEX configurations at $PAPARAZZI_HOME/conf/airframes/HooperFly

### CODE REVIEW

**Comment by flixr** [comment]
Thx!
One thing: there is no need to duplicate the jsbsim files for racerpex and teensyfly with only name changes...
It would make more sense to just make one quad and one hexa file and use them for both.

**Comment by hooperfly** [comment]
Hi Felix,Yeah, I thought about that but I think there is good reason. The current simulation models are very generic and I was curious about making more detailed FDM descriptions for the two different quad frames as well the the hexacopter frames. The chords/radius and moment couples are different for each craft. I was hoping to make more refined physical models for simulation.I also noticed some odd simulation behavior that I want to investigate a bit more to see if it's a usage error or a real issue. It's related to swapping motor rotations and how the simulations differ. I will dig into some more and let you know what I find.I will probably do an octocopter model in the next few weeks as well.Happy to be involved with the project.Regards,Rich


-------- Original Message --------
Subject: Re: [paparazzi] Added support for HooperFly Hexa and Quad
frames (#1081)

**Comment by hooperfly** [comment]
Hi Felix,To your point, I didn't add the RacerPEX specific radius/moment point modifications before submitting. I will update the RacePEX jsbsim files with the appropriate data so that it's not a duplicate of the TeensyFly files. Thanks for the input. Much appreciated.Rich


-------- Original Message --------
Subject: Re: [paparazzi] Added support for HooperFly Hexa and Quad
frames (#1081)

**Comment by hooperfly** [comment]
@flixr Over the weekend, I successfully simulated an octocopter frame as well as reorganized some files. I put all the HooperFly related jsbsim/aircraft files into a HooperFly directory to isolate them from the simple example files. If there's interest in having a "simple_x_hexa" and a "simple_x_octo" file to compliment the current set of "simple_*" files?

**Comment by flixr** [comment]
Yes, that would be great!

**Comment by hooperfly** [comment]
@flixr, I've been busy making HooperFly related airframes definitions and associated simulator aircraft definitions. One of the things that I have noticed related to rotorcraft is the variability in motor layout. Specifically, a consistent method for the location of "motor 1" in a given frame type(e.g. tri, quad, hexa, octo, custom) and configuration(e.g. +, x, other). Since I build multiple frame types of all sizes and configurations, I have adopted a convention that "motor 1" is the motor to the left or on the positive Y axis given a standard cartesian X/Y coordinate system. I also assign "motor 1" a clockwise motor spin. Motor 2-N proceed in a clockwise direction about the origin of the coordinate system and alternate spin based on their position. Do you think this a reasonable methodology to use on the Paparazzi project? Looking at the current examples, it's a bit eclectic.

**Comment by hooperfly** [comment]
@flixr, here's a link to a graphic: https://wiki.paparazziuav.org/wiki/User:Earthpatrol#Motor_Layout_Diagrams:_Quad.2C_Hexa.2C_Octo

**Comment by flixr** [comment]
Numbering is fine.
The new icons are kind of missing an indicator of where the front is, otherwise they are not very useful IMHO...
And you should [configure your git email address](https://help.github.com/articles/setting-your-email-in-git/) ;-)

**Comment by hooperfly** [comment]
@flixr I'll put the little triangle on the front of the new icons like the one on the "rotorcraft" icon. Email address configured. Thanks.

**Comment by hooperfly** [comment]
@esden @flixr Updated the icons with a "front" indicator. All of them are in the "+" configuration. What are your thoughts on having the icon reflect the frame orientation verbatim? Given the current icon template implementation, we could expand the icon names to include an orientation indicator(e.g. quadrotor & quadrotor_x, hexarotor & hexarotor_x, octorotor &octorotor_x); where "_x" denotes a frame in an "X" configuration.

**Comment by flixr** [comment]
Thx!
Regarding the icons: I personally don't care if the icon depicts a + configuration instead of X as long as I can see where the front is...
But I guess some folks might appreciated icons for X configurations...

One remaining question: do you really want/need all the test_progs in each airframe file?

**Comment by hooperfly** [comment]
@esden @flixr I need to clean up the files as I calibrate/tune each the frames flight characteristics for the Lisa MX. I will be sure to prune as I work through each and understand what is needed in each. Does that seem reasonable?

**Comment by flixr** [comment]
Sure, so I wait until you have tuned this before merging?

**Comment by flixr** [comment]
So you definitely don't need the test_progs firmware and `<autopilot name="rotorcraft_autopilot.xml" freq="512"/>` for it to function...

**Comment by hooperfly** [comment]
@flixr yes, wait to merge. I will hopefully be integrating and flight testing this weekend. I will hack out the test_progs and rotorcraft_autopilot sections as well.

**Comment by hooperfly** [comment]
@flixr I think it's good to merge. Thanks.

**Comment by flixr** [comment]
Thx! Merged with 5016dbea8ce9ba72a9f6109d293b2be85d9a3180 and 9d49af39628b7a794717bc844c2a29c3bd0da28c

**Comment by hooperfly** [comment]
@flixr it looks like the changes to acIcon.ml, acIcon.mli, and mapTrack.ml are the versions prior to the the addition of quadrotor_x, hexarotor_x, and octocopter_x. Do I need to do another pull request to get them added?

**Comment by flixr** [comment]
Ups, sorry... added with 1e4f73f4375d69d4827621e725f626bf1dfcb90e

**Comment by hooperfly** [comment]
Hi @flixr. Thanks for the merge. Github is still of the opinion that there are commits that have not been merged --> Reference the "Closed with unmerged commits" entry in this thread.

**Comment by flixr** [comment]
That is just because I didn't simply merge your commits but rebased/squashed them...

**Comment by hooperfly** [comment]
@flixr that was my assumption but wanted to verify. I will update the wiki to include the new rotor icon types: quadrotor, hexarotor, octorotor, quadrotor_x, hexarotor_x, and octorotor_x. Thanks again for all the help.

**Pull request closed without merging**
