### PR TITLE
Compile chibiOS with cpp 11

### PR DESCRIPTION
**Pull request by EwoudSmeur**
I get errors if I try to compile cpp code (EKF2) with chibios. Using cpp 11 solves it.

### CODE REVIEW

**Comment by EwoudSmeur** [comment]
Thanks for the suggestion! I tried to change it to:
`CXXSTANDARD` ?= -std=c++11
But this does not seem to have any effect...

**Comment by gautierhattenberger** [comment]
Then you have to include this flag somewhere, I don't think it is done already

**Comment by EwoudSmeur** [comment]
I added the CXXSTANDARD in the EKF2 module, since that is what needs it. Somehow adding a default does not seem to be necessary, but I can still do this if needed.

**Comment by gautierhattenberger** [comment]
let's start with this, we'll see if it is useful to make it a default later

**Pull request merged**
