### PR TITLE
Update gazebo from v7 to v8/v9 compatibility

### PR DESCRIPTION
**Pull request by kirkscheper**
Gazebo 7 is not supported on Ubuntu 18.04 (Bionic), this PR updates the function calls in the nps fdm to be compatible with Gazebo 8 and Gazebo 9. With this, gazebo is no longer compatible with installations on systems earlier than Ubuntu 16.04 (Xenial).

### CODE REVIEW

**Comment by kirkscheper** [comment]
The docker for semaphoreci needs updating, @gautierhattenberger any advice on how I can do that?

**Comment by dewagter** [comment]
also change gazebo7 into 9 in https://github.com/paparazzi/paparazzi/blob/master/.travis.yml

**Comment by gautierhattenberger** [comment]
I think you need to make a PR to update this file: https://github.com/paparazzi/paparazzi/blob/master/docker/ci/Dockerfile
Once in master, it should trigger a new build of the docker image

**Comment by kirkscheper** [comment]
Ok, well in that case this should be ready to merge, semaphore should update once merged.

**Pull request merged**
