### PR TITLE
[RTP] Revert to protocol specification: namely linearly increasing co…

### PR DESCRIPTION
**Pull request by dewagter**
…unter with 90kHz rate for FMT26. See #2068

### CODE REVIEW

**Comment by dewagter** [comment]
not tested yet

**Comment by dewagter** [comment]
This pull request reverts the change of putting the image time in milliseconds of the day multiplied by 9/100 in the RTP stream as this is not acceptable for the protocol. The RTP protocol requires a linearly increasing time stamp and it is less important that it has the correct seconds but more important that it is constant.

Changes:

 - rename: frame_number to packet number (there is no frame number, only frame time in RTP)
 - change packet_number to protocol 16bit
 - create a frame_time_counter with 90kHz resolution
 - use the VIDEO_RATE to increment it with fixed intervals
 - update all doxygen and add references to protocol docs

This code was tested on Ardrone2:

 - before this commit, I also only get the first frame and then nothing anymore
 - with this update, I get minimal delay (<0.5sec) streaming video

**Comment by OpenUAS** [comment]
Grr have missed the request, shoul refresh my browser window more often ; )

**Comment by gautierhattenberger** [comment]
is this closed with #2068 ?

**Comment by dewagter** [comment]
Yes, the patch was pushed to master separately: https://github.com/paparazzi/paparazzi/commit/57772d6a8a1ddbc17432318c94f7221c83943d97

**Pull request closed without merging**
