### PR TITLE
replace nav_utm_xxx0 with state.utm_origin_f

### PR DESCRIPTION
**Pull request by kirkscheper**
The utm position seems to use nav_utm_zone0 to compute position when a utm gps isn't present. nav_utm_XXX0 are only updated with unit_t nav_reset_utm_zone(void) which was never called so seems like this won't work when changing zones.

All ins modules set the state.tum_origin_f directly so it seems more logical to use that variable instead of the nav variables.

Additionally, the rotorcraft nav doesn't use similar variables so I thought this may help with future merging of navigation firmware.

Note: This implementation only removes the nav variables, there still isn't an implementation to check the zone and update the utm_origin_f when the zone changes.

### CODE REVIEW

**Comment by flixr** [comment]
IIRC this was done because we don't want to deal with zone crossings during flight.
So if we start close to a zone border we keep on using the original zone (i.e. we basically extend it).

@gautierhattenberger correct me if I'm wrong.

**Comment by kirkscheper** [comment]
You don't have to handle once you don't get utm messages in your gps, if you do then you have a problem...

https://github.com/paparazzi/paparazzi/tree/master/sw/airborne/subsystems/gps.c#L311

**Comment by flixr** [comment]
also nav_reset_utm_zone was added so it can be called from the flight plan...

**Comment by kirkscheper** [comment]
Also, I don't really get this... 
https://github.com/paparazzi/paparazzi/tree/master/sw/airborne/subsystems/navigation/common_nav.c#L97

This assumes that the refrence frame is always reinitialised on the ground?

**Comment by flixr** [comment]
Yes, that is currently the assumption... it's what is normally called in GeoInit, see  `NavSetGroundReferenceHere`

**Comment by kirkscheper** [comment]
I am not sure that resetting the zone makes much sense. I think you really need to move your local origin. If you just move your zone won't your waypoints be wrong. You need something like the localize_waypoints from rotorcraft.

I didn't want to actually merge the rotorcraft and fixed wing though, this is just one of those things that I saw and is really scratching at my brain.

If you want to have true zone extension then we need to recompute the zone in the utm_float_from_gps if the GPS differs from state. This will not solve any GCS messaging things though. I would however recommend replacing the update zone with update origin and move all waypoints.

I would still use the state instead of the nav_ stuff

Let me know. I am off till Sunday, so will start again after that.

**Comment by flixr** [comment]
@martinmm you requested the utm zone reset originall (see #508), do you have any feedback here?

**Comment by kirkscheper** [comment]
ok, not quite done yet but current implementation has a function to update the local position of the waypoints when you are in a different zone than in the flight plan: nav_zone_extend_waypoints. I am just not really sure when to call this, I guess you want it when you get your first gps message or something...

I also added zone extending to the utm_int_from gps so that if the zone of the vehicle is different than that of the gps, the gps position will be zone extended into the requested zone.

**Comment by flixr** [comment]
any updates here?

**Comment by kirkscheper** [comment]
I was waiting to get some feedback on if this is useful (to me it seems
that way but I don't fly across utm zones often). If this is an ok approach
I can clean it up and test it.

**Comment by flixr** [comment]
replacing the nav_utmx variables sounds good to me.
I just wouldn't remove the reset_utm_zone at this point...

@gautierhattenberger @martinmm @dewagter any comments here?

**Comment by podhrmic** [comment]
@flixr @kirkscheper do you want to fix the conflicts so we can merge it?

**Comment by gautierhattenberger** [comment]
I'm not really against this idea, but this PR needs some more work, not only solving conflicts.
And it will need some testing in real condition as it can have a few side effect.
Also I would like to have getter functions in the state interface for the reference point, instead of accessing it directly everywhere.

**Comment by OpenUAS** [comment]
If conflict resolved and some adjustment made will test moving from zone 31 to zone 32. Maybe ENAC can test from zone 31 to zone 30? (yes it is a bit of a drive from Tolouse to UTM30. And maybe DLR Munich from 32 to 33?

**Comment by OpenUAS** [comment]
@kirkscheper assigned, but feel free to re-assign. Will support you where we. Can also add more resources from the lab to close the issue. The 2SEAS project could benefit http://www.berisuas.eu/3i-2seas-uav as many more future ones.

**Comment by kirkscheper** [comment]
I don't fly fw so can't test this. I will close the PR but keep the branch alive (just in case).

**Pull request closed without merging**
