### PR TITLE
[rotorcraft] fix arming with kill switch

### LINKED ISSUE #1041: kill_switch_arming not perfect yet:
- on GPS loss -> SAFE -> LAND-DETECT -> KILL: does not unarm -> 3D Fix takes off again
 - ... ?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7056665-kill_switch_arming-not-perfect-yet?utm_campaign=plugin&utm_content=tracker%2F10895&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10895&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by flixr**
Untested, but should fix #1041

### CODE REVIEW

**Comment by flixr** [comment]
@dewagter can you please test if this solves the problem and you get the behaviour you expect?

**Comment by OpenUAS** [comment]
Weather permitting tests performed in weekend

**Comment by flixr** [comment]
@dewagter What kind of behaviour do we want in the case when it goes to FAILSAFE but does't KILL on landing (e.g. because you haven't enabled that)?
The currently proposed fix allow immediate rearming from FAILSAFE, should we also prevent it that case?

**Comment by dewagter** [comment]
If the condition that triggered the failsafe is still present, then it
should remain failsafe, otherwise immediate rearming is acceptable.

-Christophe

**Comment by flixr** [comment]
Checking which condition triggered failsafe would be a pain, but if the problem doesn't exist anymore (e.g. GPS lost), then the quad should go into the mode as set on the RC again...
So I added a check for the FAILSAFE mode.

**Pull request merged**
