### PR TITLE
Chibios update to 2.6.9.

### PR DESCRIPTION
**Pull request by podhrmic**
Update ChibiOS to 2.6.9 version, contains some bugfixes and cleanups. 
Had to remove the -Werror flag, because the ChibiOS USB driver implementation is missing a return statement in a thread which never terminates:
```
paparazzi/sw/ext/chibios/os/hal/platforms/STM32/OTGv1/usb_lld.c: In function 'usb_lld_pump':
paparazzi/sw/ext/chibios/os/hal/platforms/STM32/OTGv1/usb_lld.c:769:1: error: no return statement in function returning non-void [-Werror=return-type]
cc1: all warnings being treated as errors
```
It is not great to have errors like this, but in this case it seems to be fine. Possible solution is to ask for a fix at ChibiOS forum.

### CODE REVIEW

**Comment by podhrmic** [comment]
@gautierhattenberger any feedback on these?

**Comment by gautierhattenberger** [comment]
I was giving lectures away from my lab so I couldn't really test anything. I'll look at this tomorrow or next week. (Same for libopencm3)

**Comment by podhrmic** [comment]
@gautierhattenberger did you have a chance to test?

**Comment by gautierhattenberger** [comment]
Sorry, but it is not working with libopencm3/chibios integration we are using for SDlog. I will not have time to search for the bug before some time.
Except for the bug fix (which may not affect us because we haven't seen big problems so far), do you have a particular reason to update chibios ?

**Comment by podhrmic** [comment]
With the current version of ChibOS:
- USB-Serial is not working
- ADC driver is not working

So moving to version 2.6.9 will hopefully fix the issue (haven't had time to test it) so we will have full set of drivers. 

Just to make sure  commit #1197 didn't break SDlog, but this one does?

**Comment by gautierhattenberger** [comment]
Actually #1197 have been merged before before I could test the log, but the SDIO driver we are using is the one of ChibiOS, so updating libopencm3 should not change anything.
This pull request is not only breaking the SDlog, it is just crashing the complete autopilot after 1 or 2 seconds.
Also, what is not working with ADC ? I think the ADC driver based on ChibiOS in the rt_chibios branch is working. I don't know for the USB-serial driver.

**Comment by podhrmic** [comment]
I will look into it more then in next few days hopefully and find out what is the difference.

**Comment by OpenUAS** [comment]
@podhrmic , next few days are a bit over ;) is it still an issue? I could ask someone student to look at it ince we've already discussed it and his interest in PPRZ icm ChibiOS.

**Comment by podhrmic** [comment]
@OpenUAS since it is not going to be included in v5.6 it has lower priority. I ll get to it eventually, but you know - priorities:)

**Comment by podhrmic** [comment]
Closing for now.

**Comment by podhrmic** [comment]
Should be marked for v5.8

@gautierhattenberger can you look at where is the problem with the apogee board? All tests compile, and I dont have an Apogee board to do a live test.

**Comment by podhrmic** [comment]
Also, instead of changing the compiler settings (-Werror) I ll submit a patch to ChibiOS.

**Comment by flixr** [comment]
Should we keep this open as you guys are working on integrating chibios 3.0?

**Comment by OpenUAS** [comment]
For next PPRZ Chibi OS v3.x would make indeed more sense IMHO, Ill vote for it..

**Comment by gautierhattenberger** [comment]
Integration of CHibiOS 3 is already ongoing in the rt_paparazzi development branch, so I'm closing this PR and focus on the other branch.

**Pull request closed without merging**
