### PR TITLE
[ocaml] Fixed compilation of the sim target on OS X

### PR DESCRIPTION
**Pull request by esden**
Sim target could not find the lib-pprz.cma.

### CODE REVIEW

**Comment by flixr** [comment]
If we really want to link it statically for OSX, it should still use `-package` in the build rule instead of directly specifying the cmas...

**Comment by esden** [comment]
Yeah, I wish I could switch it over to dynamic linking. I tried to just use the same process as on linux but use dylib instead of so for the autopilot library. Sadly when this command is being run:

```

**Comment by flixr** [comment]
But even when using static linking, we should use the `-package pprz` etc arguments (instead of explicitly providing the include paths and cma files)...

**Comment by esden** [comment]
I found a solution to do dynamic linking. :)

**Comment by esden** [comment]
I have now tested the solution on linux as well as on OS X. It works for me. :)

**Comment by flixr** [comment]
I really don't like all these special cases... it makes maintenance painful.
How about rather simply always statically link? Then we also don't need to add the dllpaths (since they are not in any standard path).
See my ocamlbuild_static branch: https://github.com/flixr/paparazzi/commit/24ef86f799a6e1b55af729a2ea3aa2182a1f8916

**Comment by flixr** [comment]
Merged for now with 6a950da6f423be13969da108a013afd24527b609...

**Pull request closed without merging**
