### PR TITLE
[bebop] improve network script

### PR DESCRIPTION
**Pull request by gautierhattenberger**
- check that wifi join command is actually correct, with retries
- allow configuration for static IP

### CODE REVIEW

**Comment by EwoudSmeur** [comment]
That is some useful functionality! I was actually wondering, how is the wifi key configured? Should it be set as an environment variable via telnet?

**Comment by gautierhattenberger** [comment]
At the moment, you have to write it by end in the pprz.conf directly on the bebop. Maybe I can add the option to change the `AMODE` field from the bebop script.

**Comment by OpenUAS** [comment]
I'll will test with 4x bebop1 in on 3.9.2020 and if working honour the PR else I'll fix it

**Comment by gautierhattenberger** [comment]
just added the encryption configuration option, not tested, but the rest is working for us

**Comment by EwoudSmeur** [comment]
Superb, thanks! :smile:

**Comment by OpenUAS** [comment]
Worked can be honored. Came across some possible improvments, but if an issue will fix it and make PR or post an issue.

**Review by OpenUAS — APPROVED** [review]
Changes Worked, although if there are comments in the pprz.conf not OK but that can be fixed in another PR and issue. 

4x Bebop 1 to the router in the network all can ping eachother
working

**Pull request merged**
