### PR TITLE
[pprzlink] update to C API with file descriptor param

### PR DESCRIPTION
**Pull request by flixr**
This was already once proposed and mergd with #1589 (and reverted again) since with these changes the simulators don't work anymore.
So this needs some more work and checking before it can be integrated again.

### CODE REVIEW

**Comment by flixr** [comment]
Ok, I think I found and fixed the remaining bugs, OCaml sim and NPS are working again.
But please double check...

**Comment by gautierhattenberger** [comment]
Tested and working with:
- ocaml sim
- nps rotorcraft
- nps fixedwing
- elle0 with pprz_transport
- ardrone2 (udp, pprz)
- apogee with xbee_transport (with bug fix)
- SD logging on apogee (with bug fix)

**Comment by flixr** [comment]
Thx.
So I guess still untested are the following datalinks:
- bluegiga
- w5100
- spektrum

@kirkscheper could you test bluegiga?
@gtoonstra could you test w5100?

**Comment by gautierhattenberger** [comment]
@flixr since all transports have have been tested (and fixed) and most common devices as well, is it possible to merge this again ?
It seems that Delft team is really busy with outback challenge so they probably won't have time to test bluegiga and superbitrf (@esden ?).
Also modifications on devices where lighter than transports and I checked them again.
It is not like it is urgent for paparazzi/master, but it will make pprzlink pull requests and update easier since `fd` parameter is already in master branch there (okay this was too early as well).

**Pull request merged**
