### PR TITLE
remove nps target mavtec1

### PR DESCRIPTION
**Pull request by kirkscheper**

### CODE REVIEW

**Comment by flixr** [comment]
NPS should work just fine if you also use the radio_control spektrum for NPS.
It currently fails because you are using ppm for the nps target, but have an empty dummy radio xml file set...

**Comment by kirkscheper** [comment]
Yea, but I don't use the nps (actually never used it till now) so I won't miss this. Which do you prefer?

**Comment by flixr** [comment]
If you never use it, leave it out (will also make builds faster)...
But then it would make sense to also remove the unused simulator section...

**Comment by kirkscheper** [comment]
Done.

**Pull request merged**
