### PR TITLE
[natnet] update natnet

### PR DESCRIPTION
**Pull request by kirkscheper**
Set reference frame in lla and fix bug to set lla in deg 1e7. 
Generate correct time of week and also send that with the small messages.

### CODE REVIEW

**Comment by flixr** [comment]
Needs updated REMOTE_GPS_SMALL message, corresponding change in datalink and the math updates from #1629

**Comment by flixr** [comment]
Can you please add the required datalink changes here?

**Comment by flixr** [comment]
Can you please add the required datalink changes here and update the pprzlink submodule to paparazzi/pprzlink@fd4798cae177ca217cfb8683fb7a4a7d93a2148a ?
Then we should have everything needed here together...

**Comment by kirkscheper** [comment]
Not sure what you mean with "Can you please add the required datalink changes" As far as I see it is upto date. Could you be more specific?

**Comment by flixr** [comment]
This changes the REMOTE_GPS_SMALL message that is sent from natnet2ivy, so it needs the changed message in pprzlink and to be updated in the datalink parser...

**Comment by kirkscheper** [comment]
oh, like that. I had planned to just remove the whole thing from the datalink.c in the traffic_info pull request but I will update it here as so that we can close this.

**Pull request merged**
