### PR TITLE
Bebop i2c changes

### PR DESCRIPTION
**Pull request by martinmm**
Allow an external I2C bus connected through USB for the Bebop. Use the correct repeated-start for Transceive function for Linux targets as required by some I2C sensors.

### CODE REVIEW

**Comment by flixr** [comment]
Looks good to me, but can't test it...
The repeated start should not pose a problem for stuff that already works, right?

**Comment by martinmm** [comment]
Works for me, can see all raw sensor messages. The external I2C shows a correct repeated start on the electrical/logical level. Would be nice if someone could cross check that.

**Comment by OpenUAS** [comment]
I can cross check it, plz add used hardware details, parts, solution hickup and I can test this week.

**Comment by martinmm** [comment]
@OpenUAS Would be great if you can test normal functionality, maybe focused on the sensors that are connected through I2C. We are changing/correcting the low-level I2C protocol for transceive
from START write STOP START read STOP
to START write START read STOP
and we should make sure the hw/sw is fine with that

**Comment by OpenUAS** [comment]
OK will check normal ops

**Comment by flixr** [comment]
@OpenUAS @gautierhattenberger anyone tested this as well?

**Comment by gautierhattenberger** [comment]
It works for me

**Pull request merged**
