### PR TITLE
[can] start support of CAN for STM32F4

### PR DESCRIPTION
**Pull request by gautierhattenberger**
compiling but not tested
see #1005

### CODE REVIEW

**Comment by flixr** [comment]
Looks good to me, but also not tested since I currently don't have any CAN hardware here...

**Comment by gautierhattenberger** [comment]
I don't have CAN either. @esden do you have something to test this ? If not, do we merge it anyway (with a compile warning maybe) ?

**Comment by podhrmic** [comment]
I will be able to test it next week, so I suggest waiting....

**Comment by flixr** [comment]
@podhrmic any updates? Were you able to test?

**Comment by podhrmic** [comment]
not yet, will have to happen after the developers meeting

**Comment by podhrmic** [comment]
When trying to test it, I ran into the same issue as described in #1208 
In short, when I try to upload the code, the BMP segfaults...
```
Using Black Magic Probe with SWD on BMP_PORT /dev/ttyACM0
Using GDB = arm-none-eabi-gdb
  BMP	/home/Paparazzi/master/can_test/paparazzi/var/aircrafts/Quad_LisaMX/ap/ap.elf
Black Magic Probe (Firmware 1.5-00279-gfd9eef8, build 20141114)
Copyright (C) 2011  Black Sphere Technologies Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

Target voltage: 3.3V
Available Targets:
No. Att Driver
 1      STM32F4xx
make[1]: *** [upload] Segmentation fault (core dumped)
```

I don't know what exactly is going on, but using and older version (pre 5.4) of paparazzi, I can upload the code without any problem -  with the very same BMP and Lisa MX.

**Comment by podhrmic** [comment]
So there seems to be no support/example for CAN in libopencm3 for F4 - there are missing definitions for CAN1_GPIO_RX and CAN1_GPIO_PORT_RX (and similarly for TX). Hence the driver doesn't compile and doesn't work. This probably should be addressed in libopencm3 first. What do you think @gautierhattenberger ?

**Comment by podhrmic** [comment]
Should we close it for now or at least add milestone for later release?

**Comment by flixr** [comment]
I already changed the milestone to v5.8 for #1005

**Comment by OpenUAS** [comment]
stuffin in 5.8 really appreciated

**Comment by flixr** [comment]
closing, as we merged #1670

**Pull request closed without merging**
