### PR TITLE
HooperFly updates related to config naming convention changes

### PR DESCRIPTION
**Pull request by hooperfly**
Updates to HooperFly configuration files in support of the naming convention changes for release in v5.7

### CODE REVIEW

**Comment by flixr** [comment]
You accidentally change the commit the submodule refers to... basically you didn't call `git submodule update` when you switched branches before you committed your conf.
A `make` would have also called the submodule update for you...

So now:
git reset paparazzi/master sw/ext/mavlink
git submodule update or make
git commit (--amend)

**Comment by hooperfly** [comment]
So I issued the `git` commands you recommended and now when I try to `push` the changes, it complains about a fast-forward issue:
```
git push origin hooperfly_updates
Username for 'https://github.com': hooperfly
Password for 'https://hooperfly@github.com': 
To https://github.com/hooperfly/paparazzi.git
 ! [rejected]        hooperfly_updates -> hooperfly_updates (non-fast-forward)
error: failed to push some refs to 'https://github.com/hooperfly/paparazzi.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by flixr** [comment]
So you changed the commit (with the --amend) option... you have to force push with
git push -f
Chaning/ammending commits in pull requests is ok.

**Comment by hooperfly** [comment]
Does that new merge look right? I executed the `git push -f` and the push succeeded.

**Comment by hooperfly** [comment]
I guess it was ok. Thanks Felix.

**Pull request merged**
