### PR TITLE
Fix #2911

### LINKED ISSUE #2911: Test build fails
There is something wrong the rust key_generator which is unable to fetch packages.
```
Using "arch/stm32/px4fmu_2.4.ld" as ldscript for target "ap".
GENERATE KEYS
    Updating crates.io index
error: failed to get `rand` as a dependency of package `key_generator v0.1.0 (/home/pprz/paparazzi/sw/ext/key_generator)`

Caused by:
  failed to load source for dependency `rand`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  error reading from the zlib stream; class=Zlib (5)
Makefile.ac:189: recipe for target 'generate_keys' failed
```

### PR DESCRIPTION
**Pull request by podhrmic**
This should fix #2911

### CODE REVIEW

**Comment by podhrmic** [comment]
@fvantienen not sure if all the checks have passed, but this is at least showing a possible solution

**Comment by gautierhattenberger** [comment]
@podhrmic Travis is not used anymore (no longer free), so we need to include that to the docker image used in Semaphore. But thank you anyway for the command that we should run.

**Comment by podhrmic** [comment]
@gautierhattenberger thanks for the info! I looked at the docker image, and it looks like it is already calling the right command (see [here](https://github.com/paparazzi/paparazzi/blob/master/docker/ci/Dockerfile#L4)). Perhaps the image need to be rebuilt?

**Comment by gautierhattenberger** [comment]
It seems that docker hub is no longer doing automated builds with free plans, so the docker image is one year old now. Maybe that is the problem. I'm not that familiar with docker, so I'll need some time to find how to make the image and push it manually...

**Comment by podhrmic** [comment]
I don't seem to have permissions to push to the [paparazziuav](https://hub.docker.com/u/paparazziuav) docker hub, but rebuilding the image from scratch *should* fix the problem.

**Comment by gautierhattenberger** [comment]
The docker image is now updated with a github action.

**Pull request closed without merging**
