### PR TITLE
Fixed and tested magnetometer

### PR DESCRIPTION
**Pull request by OpenUAS**
Fixed and tested magnetometer. Tested on four different Bebop's from different batches. All is now fine, note that this is a fix for regular Bebop  and has nothing to do with Bebop2, Bebop2 is another **product,** not another version. Raw values monitored, scaled compared etc. etc.

Yes, it is only one - (minus) sign difference that make all the difference from non- autonomous flight to OK autonomous flight.

### CODE REVIEW

**Comment by OpenUAS** [comment]
Note that fix should also be backported to v5.8

**Comment by fvantienen** [comment]
Why didnt we have any problems before?

**Comment by flixr** [comment]
This is weird, it would mean that it has been wrong all along, but the bebop was flying nicely regardless...
And I doubt that has anything to do with the firmware version, right?

**Comment by OpenUAS** [comment]
Right..., @Freek, a look at the Blame and your mystery will be revealed ;) anyone flew 100% autonomous in January? Anyhow one can look oneself at RAW magneto, have a - and without and also leave on desk for 1 minute and look where your magneto goes :)

**Comment by flixr** [comment]
@OpenUAS thanks!
Seems this is a regression from commit 25fddec9d0d89a7506e1ab54bcb38a5092b9dfcc

**Comment by flixr** [comment]
Fix backported to v5.8 with 0a2c64a9a7cb6be6fbb6cdc32e2325e5a97f5d5e

**Pull request merged**
