### PR TITLE
[chibios] split FBW and AP threads

### PR DESCRIPTION
**Pull request by gautierhattenberger**
- add protection on ap and fbw state structures
- add RTOS abstraction macros
- update closing of ap/fbw threads with sdlog

### CODE REVIEW

**Comment by flixr** [comment]
Looks mostly good to me, just one thing regarding naming:
Strictly speaking mutexes are not RTOS functionality. E.g. under Linux (non-RT OS, at least without patches) we use the pthreads mutexes.
So maybe simply rename the macros to `PPRZ_MUTEX_*`?

Also before we add a lot to the old fixedwing intermcu: what is the path to common usage of the "new" subsystems/intermcu @fvantienen ?

**Comment by gautierhattenberger** [comment]
Do you have an idea about how to rename `pprz_rtos.h` ?

The intermcu subsystem seems to be very specific to PX4 boards and clones. Not sure it can fit in the fixedwing firmware easily.

**Comment by fvantienen** [comment]
It should not be specific for PX4, there is just some code in there for that that needs to be moved out. We mostly use it with the OPA autopilot (which basically is two lisa/mx's).
The new subsystem intermcu seems the way to go except that it could be converted to a module.

**Comment by flixr** [comment]
So what is missing to use it for fixedwing firmware?

**Comment by flixr** [comment]
see also #1771

**Comment by gautierhattenberger** [comment]
It can probably work on without to much effort as long as you have a physical link (uart in this case), but it is currently not really fitted for shared memory operation (mostly based on pprzlink).
So what should I do for this PR ? I won't have the time to do much more than this at the moment.
At some point, I'll have to port the chibios arch for rotorcraft as well, so I may have a look at how to merge intermcu stuff at this time.

**Comment by flixr** [comment]
Ok, so let's merge this as it is now.
But we should really follow up on a unified inter_mcu in #1771

**Pull request merged**
