### PR TITLE
[python] ivy_msg_interface: find message class by name

### PR DESCRIPTION
**Pull request by flixr**
and don't treat sender_name (first string in ivy message) as msg_class

### CODE REVIEW

**Comment by flixr** [comment]
@gautierhattenberger do you know why some datalink messages from server are sent with "sender_id" (first string) `ground` and some with `ground_dl`?
In server there is a comment that it is a "hack": https://github.com/paparazzi/paparazzi/blob/v5.8.0_stable/sw/ground_segment/tmtc/server.ml#L740

**Comment by gautierhattenberger** [comment]
From what I can see, `ground` id is used for messages from server to GCS while `ground_dl` is used for messages from server to link. At least I think it was the original idea, maybe it is not completely true now.

**Comment by flixr** [comment]
So how do you think we should handle it? Also use `ground_dl` for the `ACINFO` datalink message meant for link?
Or rather directly set `server` as sender_name?
I don't see where it would be needed to have "ground" or "ground_dl" or even why "ground_dl" was even added in the first place in 23f981b5e0ea7ab24b8d857811f15ec4dda0bb36

**Comment by flixr** [comment]
At least with this PR, the ivy_msgs_interface should handle the messages correctly and not rely on the sender_id anymore...

**Comment by gautierhattenberger** [comment]
ACINFO is going from server to link, so according to the initial idea, using `ground_dl` id is fine (seems to be the case currently).
But this PR is not about this, and your changes make things much better.

**Comment by flixr** [comment]
Thx, ACINFO is currently sent with `ground`, I'll change it to `ground_dl` to be at least consistent with the other datalink messages...

**Pull request merged**
