### PR TITLE
added flask server 

### PR DESCRIPTION
**Pull request by rmeertens**
Inspired by hooperfly who controls his drones using a flask server.... I made a flask server which can process messages. 

If you want to put stuff online, simple call this server.

### CODE REVIEW

**Comment by flixr** [comment]
please use 4 spaces for indentation of python files...

Also wondering if we should put this in pprzlink (as that is all that it depends on)

**Comment by hooperfly** [comment]
@flixr yes, we might want to come up with a plan for various new tools/services that are created using `PPRZLink`. I will be including parts @rmeertens work here into my `frc.py` handler as well. I think `PPRZLink` will be a popular interface for exploring/developing PPRZ feature sets.

**Comment by gautierhattenberger** [comment]
I agree it could be part of the tools of pprzlink

**Comment by rmeertens** [comment]
So. What to do with the pprzlink idea? Do we want to merge it here for now? Or already merge this in pprzlink...?

**Comment by gautierhattenberger** [comment]
I think can make a PR directly in pprzlink for the server itself and maybe the examples. Then you can update this pull request to update pprzlink in main paparazzi and add the tool to the control panel if you want.

**Comment by flixr** [comment]
See also paparazzi/pprzlink#2

**Comment by hooperfly** [comment]
@rmeertens I took some time this weekend to run and test your code. I like where it's going. Apropos @flixr feedback in [paparazzi/pprzlink#2](https://github.com/paparazzi/pprzlink/pull/2), it might be nice to build a streamlined example of a `flask` server that leverages various aspects of `PPRZLink` that includes a nice set of `PPRZLinkUtils` to access both static(compile-time) and dynamic(run-time) flight information.

**Comment by hooperfly** [comment]
@rmeertens I'm integrating your `flaskserver.py` concepts into the `Flying Robot Commander` server. I refactored it a bit for my use, but it's working just fine. I'm thinking about the static vs. dynamic aspects of the data model and how to gracefully mange non-runtime(pre/post flight/simulation) vs. runtime(flight/simulation). Things like the `aircraft id` have a static set view, so to speak, as well as a runtime set; where {`ac_id` runtime} <= {`ac_id` static}. So the server would only subscribe to the message bus, if there is a runtime dynamic needed.

**Comment by flixr** [comment]
closing this as it would go in pprzlink if cleaned up, see https://github.com/paparazzi/pprzlink/pull/2

**Pull request closed without merging**
