### PR TITLE
[Bebop] Camera functions

### PR DESCRIPTION
**Pull request by rmeertens**
I could be mistaken, but I think currently there are no easy functions for the camera at runtime (like: resize, move the cropped part, etc.). 
Do we want this? this pull requests lets you at least set the color gains.

### CODE REVIEW

**Comment by fvantienen** [comment]
Would be nice if we could add these functions to the camera structure. This way everyone camera can set these type of functions if they support it.

**Comment by rmeertens** [comment]
True... but we have a large potential amount of camera's... some which do support the functions we have, some not, some extra... 
Is there some generic camera library we can use? And else I suggest to implement the methods for every camera, as every camera can probably do something different.

**Comment by rmeertens** [comment]
Another idea is to create interfaces (whooo... C++?) and let each camera implement the suitable ones.

**Comment by fvantienen** [comment]
That would be best and the same for the Camera itself. So you have a main class `CameraInterface` from which the `Mt9f002` extends.

The the camera interface has functions like `setSize`, `setColorGains`, `setExposure` which all return by default something like: `CamereInterface::NOT_AVAILABLE` in the `CameraInterface` class. This way each camera can implement the functions they support.

**Comment by rmeertens** [comment]
Sounds pretty good! So for now we can still merge https://github.com/paparazzi/paparazzi/pull/1807 (as there will be some way to set the camera resolution) and close this pull request.

**Comment by flixr** [comment]
@rmeertens so close this then?

**Comment by rmeertens** [comment]
Yep, but with feedback on https://github.com/paparazzi/paparazzi/pull/1817 please ;)

**Pull request closed without merging**
