### PR TITLE
Update for Ubuntu 20.04 and GCC 9

### PR DESCRIPTION
**Pull request by gautierhattenberger**
This is basically dropping the support of Ubuntu before 16.04 and removing some compat and ocaml macros

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
We can wait a bit before merging, a colleague is testing it with 20.04

**Comment by noether** [comment]
It works for me in Ubuntu 18.04. How is it going with 20.04?

**Comment by gautierhattenberger** [comment]
We still have a few warnings to resolve, but the ground tools are almost good. I'll let you know when we are done.

**Comment by gautierhattenberger** [comment]
requires https://github.com/paparazzi/pprzlink/pull/109 for final update

**Comment by gautierhattenberger** [comment]
this one should be good, tested on 18.04 and 20.04

**Comment by gautierhattenberger** [comment]
:cry: old version from compiler don't like the `aligned` attribute used in pprzlink, and I don't really know what to do for now

**Comment by gautierhattenberger** [comment]
This time it should be fine. Tested with Ubuntu 18.04 and 20.04.
Updating:
- ocaml lib
- pprzlink
- gtk tools for deprecated functions
- gpsd, bridge and appserver
- generic device to match interface
- travis-ci with bionic

requires https://github.com/paparazzi/pprzlink/pull/110 before merging

**Pull request merged**
