### PR TITLE
replaced deprecated --force-yes command

### PR DESCRIPTION
**Pull request by matteobarbera**
Fix for Issue #2594

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
It seems that the problem is coming from gazebo package from ROS. The version for 18.04 bionic have been update the Oct 3, 2020, but the reference to dependency packages seems to be broken (`9.15.0-1~bionic` replaced by `9.15.0-2~bionic`). Maybe it will solve by itself when they fix the problem.
Or we could use the version from ubuntu which is much older (`9.0.0+dfsg5-3ubuntu1`). Is it problem ? Since it is only for compilation tests, maybe it is good enough.

**Comment by dewagter** [comment]
Since only for compilation tests, the old version is OK if it compiles.

**Comment by gautierhattenberger** [comment]
@matteobarbera can you try to update your PR without adding the ROS/Gazebo repository to the travis config ?

**Comment by matteobarbera** [comment]
@gautierhattenberger do you mean removing the Gazebo repository from the pre-install commands? 

https://github.com/paparazzi/paparazzi/blob/fab125357423147bb5962d6d174ae5d4e4feb1ac/.travis.yml#L10-L11

It seems that this is a recurring issue, and is being addressed https://github.com/osrf/gazebo/issues/2744 and https://github.com/ignition-tooling/release-tools/issues/307

**Comment by gautierhattenberger** [comment]
yes, remove the Gazebo repository, it should use the (old) version from ubuntu

**Comment by matteobarbera** [comment]
The Travis job log shows that the different Gazebo packages were taken from the much older Ubuntu versions as you expected
`Get:101 http://archive.ubuntu.com/ubuntu bionic/universe amd64 gazebo9-common all 9.0.0+dfsg5-3ubuntu1 [34.4 MB]`

**Review by gautierhattenberger — APPROVED** [review]
it seems fine to use old gazebo for compilation tests

**Pull request merged**
