### PR TITLE
[video_capture] recovered saving of exif information

### PR DESCRIPTION
**Pull request by wilcoschoneveld**
This PR recovers the video_exif functionality that was left out in the computer vision pipeline update.

### CODE REVIEW

**Comment by flixr** [comment]
Nice, please add the new define to the doc section of the module...

**Comment by wilcoschoneveld** [comment]
I believe the intended usage of the video_exif module is to add it to the airframe and it will place the define itself, so that the video_capture module responds accordingly. I'm not sure if there are guidelines for this kind of behavior but I added a doc line anyways.

**Comment by dewagter** [comment]
I do not think adding a non-existing define to docs is a good idea. I'd suggest to add the description to the docs instead: "To save EXIF data, include the exif module", of have the define (probably a configure then?) auto-include the module if that is at all possible.

**Comment by flixr** [comment]
The define exists... but yes it is automatically set if you add the video_exif module.
So I agree with @dewagter here that a comment in the description makes more sense.
Also a comment in the code where this define is checked would be nice (to indicate that the user is not expected to set this define, but that it is added if the video_exif module is loaded.

**Comment by wilcoschoneveld** [comment]
Thanks for the pointers.

**Pull request merged**
