### PR TITLE
[modules] system identification update

### PR DESCRIPTION
**Pull request by dewagter**
extra system_identification
 - [x] merge https://github.com/paparazzi/pprzlink/pull/175
 - [x] update pprzlink

### CODE REVIEW

**Review by dewagter — COMMENTED** [review]
It would be cleaner to convert the name of the files to something more specific.

**Comment by fvantienen** [comment]
Message is merged, so pprzlink can be updated

**Review by fvantienen — DISMISSED** [review]

**Review by fvantienen — APPROVED** [review]

**Review by gautierhattenberger — APPROVED** [review]

**Comment by gautierhattenberger** [comment]
I will only merge PR that have no significant impact on the system or with low risk of breaking confs  until next month. The credits on Semaphore CI are finished for the free plan for this month...

**Comment by dewagter** [comment]
I will run ```make test``` on all branches

**Pull request merged**
