### PR TITLE
fixes for using wxPython 3.0 (python-wxgtk3.0)

### LINKED ISSUE #1435: [python] messages/settings not working with wxgtk3.0
From message app:
>
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py",
> line 16763, in <lambda>
>     lambda event: event.callable(*event.args, **event.kw) )
>   File
> "/home/garciafa/paparazzi/sw/ground_segment/python/messages_app/messagesframe.py",
> line 149, in gui_update
>     self.add_new_message(aircraft, msg.msg_class, msg.name)
>   File
> "/home/garciafa/paparazzi/sw/ground_segment/python/messages_app/messagesframe.py",
> line 137, in add_new_message
>     grid_sizer.AddGrowableCol(1)
>   File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py",
> line 15364, in AddGrowableCol
>     return _core_.FlexGridSizer_AddGrowableCol(*args, **kwargs)
> wx._core.PyAssertionError: C++ assertion "!IsColGrowable( idx )"
> failed at ../src/common/sizer.cpp(1976) in AddGrowableCol():
> AddGrowableCol() called for growable column

Which looks like API inconsistencies...

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28499043-python-messages-settings-not-working-with-wxgtk3-0?utm_campaign=plugin&utm_content=tracker%2F10895&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10895&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by flixr**
Trying to fix #1435

### CODE REVIEW

**Comment by garciafa** [comment]
I still have this error on message app :
> Traceback (most recent call last):
>  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16763, in <lambda>
>     lambda event: event.callable(*event.args, **event.kw) )
>   File "/home/garciafa/paparazzi/sw/ground_segment/python/messages_app/messagesframe.py", 
> line 155, in gui_update
>     aircraft.messages_book.SetPageImage(aircraft.messages[msg.name].index, 1)
>   File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 13560, in SetPageImage
>     return _core_.BookCtrlBase_SetPageImage(*args, **kwargs)
> wx._core.PyAssertionError: C++ assertion "page < GetPageCount()" failed at ../src
> /gtk/notebook.cpp(276) in SetPageImage(): invalid notebook index

It does print the messages though. It seem not to be updating the image next to each message (it turns green but does not change when the message is not seen for some time)

Settings app seem to be working without errors

**Comment by flixr** [comment]
Hm.... there must have been an earlier error causing this, maybe in `find_page`
A bit hard to fix without having wxPython 3 and actually being able to debug it...

**Comment by garciafa** [comment]
Le 23/11/2015 15:01, Felix Ruess a écrit :
>
> Hm.... there must have been an earlier error causing this, maybe in
> |find_page|
> A bit hard to fix without having wxPython 3 and actually being able to
> debug it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paparazzi/paparazzi/pull/1438#issuecomment-158939583>.
>
I'm not a python programmer and am busy correcting exams right now.

but if I manage to get some time off next week, I'll try and see if I
can debug that.

Fabien

**Comment by garciafa** [comment]
I managed to find the problem.
It comes from the index used in aircraft.messages_book.SetPageImage calls.
I have modified the code so as to remove one to the index and it works as it should (image are updated from green to gray and no more error messages). The index of the messages start at 1 and the messages of the images at 0.

Here is a patch (two lines modified) :
[patch.txt](https://github.com/paparazzi/paparazzi/files/47130/patch.txt)

**Comment by flixr** [comment]
Ah, thx for finding that. Funny that this didn't give an error before...
Anyway, I fixed the find_page function instead.

**Comment by flixr** [comment]
@garciafa if you could confirm that this fix also works for you we can merge :-)

**Comment by garciafa** [comment]
I just checked and it fixes message_app. Sorry for not finding the origin in find_page :/
I talked with Gauthier earlier, I will try and make pull requests from my repository from now on instead of posting patches.

**Comment by flixr** [comment]
No worries, thanks for finding and testing!

**Pull request merged**
