### PR TITLE
[fg] Updated flight gear interface and removed obsolete HITL files

### PR DESCRIPTION
**Pull request by podhrmic**
flight_gear.h updated to new version to be compatible with flight gear net_FDM
Removed obsolete HITL files that stayed here just for legacy reason.

### CODE REVIEW

**Comment by flixr** [comment]
why also delete the start_fg.sh script?

**Comment by gautierhattenberger** [comment]
It was exactly doing what was expected when trying to load the mikrokopter model. I agree we should have a script to easily start flightgear, but can we try to make it better first ? Like looking into the airframe file for the correct model if a name is passed as argument.

**Comment by podhrmic** [comment]
No program used it directly (like a "launch" button in pprzi), and it wasn't mentioned in the wiki either - so I assumed it was obsolete. But I agree with @gautierhattenberger that we should have something more flexible than that.

**Comment by flixr** [comment]
For which Flight Gear versions was this change needed? What is the minimum FG version now?

**Comment by podhrmic** [comment]
3.4. The difference is in NetFDM interface, and has been there at least sine fg 2.6 
NetGui (what NPS is currently using) has not changed.

**Comment by flixr** [comment]
ok, thanks for clearing that up

**Pull request merged**
