### PR TITLE
Updated osd files and a new module

### PR DESCRIPTION
**Pull request by hendrixgr**
Hi.
The OSD files are much improved, magnetic course indication is added,, the home direction indication is changed and a new module for recovering the UAV is added.
I have heavily tested the OSD (with PAL camera, NTSC has 13 rows instead the 15 of PAL) and lightly the UAV recovery module
which works fine so far.

### CODE REVIEW

**Comment by hendrixgr** [comment]
I live it at your discretion what to include and what not, i just want to contribute as much as possible.
Anyway the OSD is greatly improved and tested.

**Comment by gautierhattenberger** [comment]
I'll have a look at this next week hopefully...

**Comment by hendrixgr** [comment]
No problem at all!
Chris

**Comment by gautierhattenberger** [comment]
is this closed and replaced by #2614  ?

**Comment by hendrixgr** [comment]
Yes it is the same request, i deleted the previous one when i was trying to find why the build in Semaphore only fails.
It is still failing, something to do with adrone2 opticflow.

**Comment by gautierhattenberger** [comment]
Okay, then I'm closing this one and only review the other one
The CI fail is not related, although I don't know why either, most likely related to a wrong dependency in the build somewhere. If I run by hand on Semaphore, it always works....

**Pull request closed without merging**
