### PR TITLE
[ground] Add heading to ublox2ivy

### PR DESCRIPTION
**Pull request by fvantienen**
Should be merged after https://github.com/paparazzi/pprzlink/pull/164

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
It seems that `sw/ground_segment/tmtc/gpsd2ivy.c` is also sending the TARGET_POS message and it should be updated as well

**Comment by fvantienen** [comment]
Updated gpsd2ivy as well, since it doesn't have heading information it sends NAN. That way the autopilot knows that it doesn't have heading information.

**Comment by gautierhattenberger** [comment]
you can update the pprzlink ref now, after that it can be merged

**Comment by fvantienen** [comment]
Updated the reference

**Review by gautierhattenberger — APPROVED** [review]

**Pull request merged**
