### PR TITLE
[ChibiOS] Test telemetry

### PR DESCRIPTION
**Pull request by podhrmic**
I added telemetry test (save as in Lisa example - should just send ALIVE messages). 

**Update:** All it needed was  ```uart_periph_init()```, now it works like a charm

~~However, it doesnt't work and I was able to track it here:~~

~~In var/include/messages.h is ```DOWNLINK_SEND_ALIVE``` defined as~~
```
#define DOWNLINK_SEND_ALIVE(_trans, _dev, nb_md5sum, md5sum) pprz_msg_send_ALIVE(&((_trans).trans_tx), &((_dev).device), AC_ID, nb_md5sum, md5sum)
static inline void pprz_msg_send_ALIVE(struct transport_tx *trans, struct link_device *dev, uint8_t ac_id, uint8_t nb_md5sum, uint8_t *_md5sum) {
	if (trans->check_available_space(trans->impl, dev, trans->size_of(trans->impl, 0+1+nb_md5sum*1 +2 /* msg header overhead */))) {
	  trans->count_bytes(trans->impl, dev, trans->size_of(trans->impl, 0+1+nb_md5sum*1 +2 /* msg header overhead */));
	  trans->start_message(trans->impl, dev, 0+1+nb_md5sum*1 +2 /* msg header overhead */);
	  trans->put_bytes(trans->impl, dev, DL_TYPE_UINT8, DL_FORMAT_SCALAR, 1, &ac_id);
	  trans->put_named_byte(trans->impl, dev, DL_TYPE_UINT8, DL_FORMAT_SCALAR, DL_ALIVE, "ALIVE");
	  trans->put_bytes(trans->impl, dev, DL_TYPE_ARRAY_LENGTH, DL_FORMAT_SCALAR, 1, (void *) &nb_md5sum);
	  trans->put_bytes(trans->impl, dev, DL_TYPE_UINT8, DL_FORMAT_ARRAY, 1 * nb_md5sum, (void *) _md5sum);
	  trans->end_message(trans->impl, dev);
	} else
	  trans->overrun(trans->impl, dev);
}
```

~~The function hangs in the first line ```trans->check_available_space``` - looks like the pointers or callbacks are not properly initialized. I call ```downlink_init()``` as I am supposed to, and the defines are correct:~~
```
test/chibios_test_telemetry.c:43:1: note: #pragma message: Config: DefaultChannel = pprz_tp
test/chibios_test_telemetry.c:44:1: note: #pragma message: Config: DefaultDevice = uart3
test/chibios_test_telemetry.c:45:1: note: #pragma message: Config: MD5SUM = ((uint8_t*)"\262\070\301\364\064\162\052\357\300\333\252\370\070\014\152\103")
test/chibios_test_telemetry.c:46:1: note: #pragma message: Config: AC_ID = 16
```

~~Do you know what else has to be initialized in order to get donwlink running?~~

### CODE REVIEW

**Comment by podhrmic** [comment]
Finally fixed, telemetry test works now. Sorry for the multiple commits.

**Comment by flixr** [comment]
You also put the downlink in a separate thread, was that needed?

**Comment by flixr** [comment]
Merged with 5809846b23dad67fff611d9bc05df7229ee13412 and 0259234424a8839ca5c48f686129ca7af50cbeda

**Comment by podhrmic** [comment]
The separate thread is not really necessary, it was just for clarity.

**Pull request closed without merging**
