### PR TITLE
Added test for aggieair config

### PR DESCRIPTION
**Pull request by podhrmic**
Added a test for aggie_air conf. It really helps me with development, and it does't hurt anyone.

Indeed, if each developer has their own conf test it would be probably too much, but I don't think that is likely to happen.

### CODE REVIEW

**Comment by podhrmic** [comment]
@flixr are you cool with this?

**Comment by gautierhattenberger** [comment]
I don't mind adding this but what is the reason ? you want to run this on a CI server ?

**Comment by flixr** [comment]
I also don't really mind one more test target, but I want to avoid the situation where we start adding this for every conf...
For my conf I simply made an alias in my .zshrc (for you probably .bashrc) to avoid having to type so much...

**Comment by podhrmic** [comment]
@flixr would you mind sharing an example?

**Comment by flixr** [comment]
Added to my `.zshrc`:
```
alias pprz_flixr='CONF_XML=conf/airframes/FLIXR/flixr_conf.xml prove tests/aircrafts/'
```
I think for bash the alias definition is the same....

**Comment by podhrmic** [comment]
And then how do you use it? `make pprz_flixr` doesn't' seem to work for me:-/

**Comment by flixr** [comment]
just `pprz_flixr`... it's a stupid name, I should have better called it something like `test_flixr` or so...
You type in a shell alias as if it was a command, and the shell will simply replace it by what you set the alias to...

**Comment by flixr** [comment]
So we can close this then?

**Comment by podhrmic** [comment]
Actually I would prefer to merge this - you need to set up your PPRZ_HOME and PPRZ_SRC to get it working, and I have multiple clones of pprz on my computer, so it would be harder to set it up. Is that cool?

**Comment by flixr** [comment]
Fair enough...

**Pull request merged**
