### PR TITLE
Feed forward guidance

### PR DESCRIPTION
**Pull request by dewagter**
@EwoudSmeur should this be implemented differently?

### CODE REVIEW

**Comment by EwoudSmeur** [comment]
Haha see #3054

**Comment by dewagter** [comment]
Sorry, I missed that this had been proposed before.

Can this become an issue then?

**Comment by dewagter** [comment]
Wiil fix this PR.

**Comment by dewagter** [comment]
@gautierhattenberger is this proposition better, or even worse?

In the long run, passing extra information to innerloops should be the way to go: the guidance already knows things the feedback controller in the inner loop can not know yet: e.g. when following trajectories like in https://doi.org/10.1109/ICRA.2011.5980409

For the generic future version of ```stabilization.h```, besides rates_ff, the desired angular acceleration would also be nice to pass.

**Comment by dewagter** [comment]
Legend:
--------
 - ```ATT``` setpoint and ```RATE=0``` -> normal attitude feedback
 - ```RATE``` setpoint and no ```ATT``` -> normal rate feedback
 - ```ATT``` and ```RATE```, then -> ATT feedback with RATE Feed-Forward

*When using stabilization with a reference model, the FF is probably overruled, as the reference lags behind the setpoint.*

**Comment by EwoudSmeur** [comment]
Right now we have the reference model, which can perform a similar function: calculate feed forward references for e.g. rates or velocities, in order to track the reference. But this is a function that could also be taken by other methods, e.g. a 4D trajectory, vector field, or some other algorithm that can compute feed forward commands. I think it would be better to make one structure with which these different methods can interact with the reference.

The references that are not set during the control loop should be set to zero, such that the controller doesn't use them. I think this would make it much easier to implement and switch between different tracking methods.

**Review by gautierhattenberger — DISMISSED** [review]
I'm fine with this implementation until the new stabilization structure is finished.

**Review by gautierhattenberger — APPROVED** [review]

**Review by gautierhattenberger — APPROVED** [review]

**Pull request merged**
