### PR TITLE
[rotorcraft] heading integration protection in RC-event

### LINKED ISSUE #452: heading integration protection in RC-event
https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.c#L105

The PSI += .... is highly depending on the RC-frame rate. With most RC this is not a problem but with variable message rates (e.g. rc_datalink dropping messages or joysticks sending too many frames) this line becomes dangerous.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/925828-heading-integration-protection-in-rc-event?utm_campaign=plugin&utm_content=tracker%2F10895&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10895&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by flixr**
The PSI += .... was highly depending on the RC-frame rate.
With most RC this is not a problem but with variable message rates (e.g. rc_datalink dropping messages or joysticks sending too many frames) this line becomes dangerous.

So measure the time between to calls to read_rc_setpoint function instead of using a fixed RC_UPDATE_FREQ.
To prevent really weird things from happening, bound dt to 0.5s.

Don't partuculariliy like that this pulls in the sys_time dependency here,
but couldn't think of something better...

should close #452

### CODE REVIEW

**Comment by OpenUAS** [comment]
Ah, great so much welcomed, thx!

**Comment by flixr** [comment]
@gautierhattenberger what do you think?

**Comment by gautierhattenberger** [comment]
The only addition I can see is to keep the possibility of a fixed `dt`, in case your very confident and want to avoid jitter (can this really happen ?)

**Comment by flixr** [comment]
Keeping possibility for fixed DT could be done, but I would say we add this only if someone actually needs it....

**Pull request merged**
