### PR TITLE
[tag tracking] Compute tag orientation.

### PR DESCRIPTION
**Pull request by Fabien-B**
Not tested yet.

### CODE REVIEW

**Comment by dewagter** [comment]
Currently in master:

conf/airframes/ENAC/conf_enac.xml:
---------------------------------
 -  ANTON --- ap
	- [ ] ``` /home/mavlab/paparazzi/var/aircrafts/ANTON/ap/generated/flight_plan.h:870:15: error: 'tag_tracking' undeclared (first use in this function); did you mean 'tag_tracking_kp'? ```
 -  ANTON --- nps
	- [ ] ``` /home/mavlab/paparazzi/var/aircrafts/ANTON/nps/generated/flight_plan.h:870:15: error: ‘tag_tracking’ undeclared (first use in this function); did you mean ‘tag_tracking_kp’? ```
 -  CobraV2 --- ap
	- [ ] ``` modules/computer_vision/tag_tracking.c:191:2: error: #error "TAG_TRACKING_NB_WP_MAX not defined!" ```
	- [ ] ``` modules/computer_vision/tag_tracking.c:307:40: warning: unused parameter 'tag_info' [-Wunused-parameter] ```
 -  CobraV2 --- nps
	- [ ] ``` modules/computer_vision/tag_tracking.c:191:2: error: #error "TAG_TRACKING_NB_WP_MAX not defined!" ```
	- [ ] ``` modules/computer_vision/tag_tracking.c:307:40: warning: unused parameter ‘tag_info’ [-Wunused-parameter] ```
 -  MAYA --- ap
	- [ ] ``` modules/computer_vision/tag_tracking.c:191:2: error: #error "TAG_TRACKING_NB_WP_MAX not defined!" ```
	- [ ] ``` modules/computer_vision/tag_tracking.c:307:40: warning: unused parameter 'tag_info' [-Wunused-parameter] ```
 -  MAYA --- nps
	- [ ] ``` modules/computer_vision/tag_tracking.c:191:2: error: #error "TAG_TRACKING_NB_WP_MAX not defined!" ```
	- [ ] ``` modules/computer_vision/tag_tracking.c:307:40: warning: unused parameter ‘tag_info’ [-Wunused-parameter] ```
 -  RoBoBee --- ap
	- [ ] ``` modules/computer_vision/tag_tracking.c:191:2: error: #error "TAG_TRACKING_NB_WP_MAX not defined!" ```
	- [ ] ``` modules/computer_vision/tag_tracking.c:307:40: warning: unused parameter 'tag_info' [-Wunused-parameter] ```
 -  RoBoBee --- nps
	- [ ] ``` modules/computer_vision/tag_tracking.c:191:2: error: #error "TAG_TRACKING_NB_WP_MAX not defined!" ```
	- [ ] ``` modules/computer_vision/tag_tracking.c:307:40: warning: unused parameter ‘tag_info’ [-Wunused-parameter] ```

**Comment by Fabien-B** [comment]
@dewagter Could you test that the errors you mentioned are fixed in this PR ?
I have some unrelated issues running `make test_all_confs` (something with opencv)

**Comment by dewagter** [comment]
Dear @Fabien-B : I tested this branch commit 4f4877bf11fb23c6608e92e02016f402fd726743

```
************
Testing all aircrafts in conf: conf/airframes/ENAC/conf_enac.xml
************
tests/aircrafts/01_compile_all_aircrafts.t .. 1/19 # compiling AIRCRAFT: [ANTON] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 2/19 # compiling AIRCRAFT: [ANTON] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 3/19 # compiling AIRCRAFT: [CYFOAM] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 4/19 # compiling AIRCRAFT: [CYFOAM] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 5/19 # compiling AIRCRAFT: [CobraV2] TARGET: [ap]

Warning: AIRCRAFT=CobraV2 target=ap compiled sucessfully but had warnings:
modules/computer_vision/tag_tracking.c:325:40: warning: unused parameter 'tag_info' [-Wunused-parameter]
  325 | static void update_wp(struct tag_info* tag_info, bool report UNUSED)
      |                       ~~~~~~~~~~~~~~~~~^~~~~~~~


tests/aircrafts/01_compile_all_aircrafts.t .. 6/19 # compiling AIRCRAFT: [CobraV2] TARGET: [nps]

Warning: AIRCRAFT=CobraV2 target=nps compiled sucessfully but had warnings:
modules/computer_vision/tag_tracking.c:325:40: warning: unused parameter ‘tag_info’ [-Wunused-parameter]
  325 | static void update_wp(struct tag_info* tag_info, bool report UNUSED)
      |                       ~~~~~~~~~~~~~~~~~^~~~~~~~


tests/aircrafts/01_compile_all_aircrafts.t .. 7/19 # compiling AIRCRAFT: [FALCON_V2] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 8/19 # compiling AIRCRAFT: [FALCON_V2] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 9/19 # compiling AIRCRAFT: [MAYA] TARGET: [ap]

Warning: AIRCRAFT=MAYA target=ap compiled sucessfully but had warnings:
modules/computer_vision/tag_tracking.c:325:40: warning: unused parameter 'tag_info' [-Wunused-parameter]
  325 | static void update_wp(struct tag_info* tag_info, bool report UNUSED)
      |                       ~~~~~~~~~~~~~~~~~^~~~~~~~


tests/aircrafts/01_compile_all_aircrafts.t .. 10/19 # compiling AIRCRAFT: [MAYA] TARGET: [nps]

Warning: AIRCRAFT=MAYA target=nps compiled sucessfully but had warnings:
modules/computer_vision/tag_tracking.c:325:40: warning: unused parameter ‘tag_info’ [-Wunused-parameter]
  325 | static void update_wp(struct tag_info* tag_info, bool report UNUSED)
      |                       ~~~~~~~~~~~~~~~~~^~~~~~~~


tests/aircrafts/01_compile_all_aircrafts.t .. 11/19 # compiling AIRCRAFT: [PANACHE_1] TARGET: [ap]
tests/aircrafts/01_compile_all_aircrafts.t .. 12/19 # compiling AIRCRAFT: [PANACHE_1] TARGET: [nps]
tests/aircrafts/01_compile_all_aircrafts.t .. 13/19 # compiling AIRCRAFT: [RoBoBee] TARGET: [ap]

Warning: AIRCRAFT=RoBoBee target=ap compiled sucessfully but had warnings:
modules/computer_vision/tag_tracking.c:325:40: warning: unused parameter 'tag_info' [-Wunused-parameter]
  325 | static void update_wp(struct tag_info* tag_info, bool report UNUSED)
      |                       ~~~~~~~~~~~~~~~~~^~~~~~~~

```

**Comment by Fabien-B** [comment]
Ok, I see, it's indeed unused if TAG_TRACKING_WPS is not defined.
Fixed in 272e4a8271b02be861850aedfb9ff28df8268701.

**Review by dewagter — APPROVED** [review]

**Pull request merged**
