### PR TITLE
[computer vision] Driver addition for mateksys_PMW3901_l0x

### PR DESCRIPTION
**Pull request by pcampolucci**
follow up from https://github.com/paparazzi/paparazzi/pull/2639

Submodule of ppzlink updated to latest version

### CODE REVIEW

**Comment by pcampolucci** [comment]
@gautierhattenberger this is the final one. Hope I did not forget anything

**Comment by gautierhattenberger** [comment]
almost, pprzlink ref is good, but the `key_generator` submodule have been rewind to your backup branch version

**Comment by pcampolucci** [comment]
ok done

**Comment by pcampolucci** [comment]
@gautierhattenberger it fails again. It builds on my machine. I am out of ideas D:

**Comment by gautierhattenberger** [comment]
I missed the modified ABI message, it has one extra parameter, so now it is failing with other modules using it:
```
 grep -r MsgOPTICAL_FLOW *
modules/computer_vision/opticflow_module.c:    AbiSendMsgOPTICAL_FLOW(FLOW_OPTICFLOW_ID, now_ts,
modules/sensors/opticflow_pmw3901.c:  AbiSendMsgOPTICAL_FLOW(FLOW_OPTICFLOW_PMW3901_ID,
modules/ctrl/optical_flow_landing.c:  AbiBindMsgOPTICAL_FLOW(OFL_OPTICAL_FLOW_ID, &optical_flow_ev, vertical_ctrl_optical_flow_cb);
modules/ctrl/optical_flow_hover.c:  AbiBindMsgOPTICAL_FLOW(OFH_OPTICAL_FLOW_ID, &optical_flow_ev, ofh_optical_flow_cb);
modules/stereocam/stereocam.c:    AbiSendMsgOPTICAL_FLOW(STEREOCAM2STATE_SENDER_ID, now_ts,
```

**Comment by pcampolucci** [comment]
Oh these are new from the updated master, I will just remove the distance_quality parameter then. Its not that important

**Comment by pcampolucci** [comment]
@gautierhattenberger It works!

**Review by gautierhattenberger — APPROVED** [review]
good job

**Pull request merged**
