### PR TITLE
Update AggieAir config

### PR DESCRIPTION
**Pull request by podhrmic**
Regular update of Aggieair's config files and airframes

### CODE REVIEW

**Comment by podhrmic** [comment]
@gautierhattenberger any comments on this?

**Comment by gautierhattenberger** [comment]
would it possible to move the modules from the `modules` node of your airframe files to the `firmware` part or is this making issues ?

**Comment by podhrmic** [comment]
Done. Remind me, what is the reason for moving all the `module` nodes into firmware section?

**Comment by podhrmic** [comment]
@gautierhattenberger do you approve?

**Pull request merged**
