### PR TITLE
Modules makefile improvements

### PR DESCRIPTION
**Pull request by gautierhattenberger**
Two improvements for the makefile section of modules in order to efficiently replace subsystems:
* case modifier for upper/lower version makefile variables: much cleaner xml code
* add firmware option to allow a single module to handle specific firmware options

### CODE REVIEW

**Comment by flixr** [comment]
Very nice!

Just wondering if we maybe should make `default="TRUE"` the default, since that is probably used with nearly every configure option that sets a value.
E.g. replace it by something like `set="TRUE"` for the case where you don't want to specify a default value with `?=`

**Comment by gautierhattenberger** [comment]
I guess we can change this. The only point I see is that `configure` will have different behavior if they come from airframe file (regular variable) or from the module (optional variable). If you're fine with this, I can change it.

**Comment by flixr** [comment]
Good point.
I think even nicer to use would be
`<configure name="FOO_I2C_DEV" default="i2c0" case="upper|lower"/>`
and it wouldn't collide with `<configure name="BAR" value="BAZ"/>` as  the airframe file.

**Comment by gautierhattenberger** [comment]
Can I merge like this ?

**Comment by flixr** [comment]
:+1:

**Pull request merged**
