### PR TITLE
[logalizer] rename plot to logplotter for clarity

### PR DESCRIPTION
**Pull request by flixr**
Was quite unclear that `plot` refers to the log plotter and `plotter` to the realtime plotter...
Hence rename the `plot` executable to `logplotter`

### CODE REVIEW

**Comment by esden** [comment]
:+1: from me! :smile:

**Comment by flixr** [comment]
@gautierhattenberger what do you think?
Should we add a symlink to `plot` so it still works with old sessions (control panel files)?

**Comment by esden** [comment]
Can we put a placeholder in that place instead, that prints out an error indicating the name change and what needs to be done?

**Comment by flixr** [comment]
Done, if launched via the old `plot` it will print that plot was renamed to logplotter and then launch logplotter.

**Comment by flixr** [comment]
@gautierhattenberger any comments?

**Comment by gautierhattenberger** [comment]
Fine for me

**Comment by hooperfly** [comment]
@flixr the usage message needs to be updated apropo:

```
$ ./sw/logalizer/logplotter  -help
Usage: plot <log files>
  -export_csv Export in CSV in batch mode according to saved preferences (conf/%gconf.xml)
  -v Verbose
  -help  Display this list of options
  --help  Display this list of options
```

**Comment by flixr** [comment]
Thx, fixed.

**Pull request merged**
