### PR TITLE
[intermcu][datalink] fix

### PR DESCRIPTION
**Pull request by dewagter**

### CODE REVIEW

**Comment by flixr** [comment]
Looks like adding DatalinkEvent again was accidental...

**Comment by dewagter** [comment]
yes, this code should have been merged prior to #1835
what should it be now?

**Comment by flixr** [comment]
I guess you only want to add the intermcu_periodic... but not sure what your original problem and fix was...

**Comment by dewagter** [comment]
@fvantienen

**Comment by gautierhattenberger** [comment]
If this is all you need, it is fine for merging

**Pull request merged**
