### PR TITLE
cleaned up version of Vectornav VN-200

### PR DESCRIPTION
**Pull request by flixr**
slightly cleaned up version of #1305

some AHRS stuff can probably also be removed...

### CODE REVIEW

**Comment by podhrmic** [comment]
I see. Do you want to merge it as is?

**Comment by flixr** [comment]
Could you plz test it?

**Comment by podhrmic** [comment]
it works for rotorcraft (test airframe is Ark_Quad from aggieair_conf), but for fixedwing (Minion_Lia) it says:
```
RUN 'make -C /home/fwmav/Paparazzi/master/vectornav_test/paparazzi -f Makefile.ac AIRCRAFT=Minion_Lia ap.compile '
make: Entering directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi'
-----------------------------------------------------------------------
Paparazzi version v5.7_devel-68-g1830420-dirty
-----------------------------------------------------------------------
#######################################
# BUILD AIRCRAFT=Minion_Lia, TARGET ap
#######################################
Info: settings '/home/fwmav/Paparazzi/master/vectornav_test/paparazzi/conf/settings/nps.xml' unloaded for target 'ap'
make[1]: Entering directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi'
GENERATE autopilots in /home/fwmav/Paparazzi/master/vectornav_test/paparazzi/var/aircrafts/Minion_Lia/ap/generated/
make[1]: Leaving directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi'
make[1]: Entering directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi'
make[1]: Nothing to be done for `radio_ac_h'.
make[1]: Leaving directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi'
make[1]: Entering directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi'
make[1]: Nothing to be done for `flight_plan_ac_h'.
make[1]: Leaving directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi'
cd sw/airborne; make -j8 TARGET=ap all
Using "arch/stm32/lisa-mx.ld" as ldscript for target "ap".
make[1]: Entering directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi/sw/airborne'

make[1]: *** No rule to make target `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi/var/aircrafts/Minion_Lia/ap/ap.elf', needed by `elf'.  Stop.
make[1]: *** Waiting for unfinished jobs....
GCC version: arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 224288] 

make[1]: Leaving directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi/sw/airborne'
make: *** [ap.compile] Error 2
make: Leaving directory `/home/fwmav/Paparazzi/master/vectornav_test/paparazzi'

FAILED 'make -C /home/fwmav/Paparazzi/master/vectornav_test/paparazzi -f Makefile.ac AIRCRAFT=Minion_Lia ap.compile' with code 2
```

**Comment by flixr** [comment]
Ups, should be fixed...

**Comment by podhrmic** [comment]
Tested, works now.

**Pull request merged**
