### PR TITLE
GVF user configs and GVF Viewer documentation

### PR DESCRIPTION
**Pull request by jesusBV20**
I just pushed a user config that will allow everyone to test some GVF features in simulation.

### CODE REVIEW

**Comment by noether** [comment]
Maybe, it would be a good idea to leave

**Comment by noether** [comment]
wrong button :P

**Comment by jesusBV20** [comment]
I'm working on the documentation of GVF Viewer and I would like to push the changes here. Could you wait to merge this branch with master until I publish the documentation files?

**Comment by gautierhattenberger** [comment]
@jesusBV20 can you tell me when it is ready for review ?

**Comment by jesusBV20** [comment]
> @jesusBV20 can you tell me when it is ready for review ?

Sure, I will tell you.

**Comment by gautierhattenberger** [comment]
@jesusBV20 is it ready or this needs some more work ?

**Comment by jesusBV20** [comment]
> @jesusBV20 is it ready or this needs some more work ?

Hi Gautier. It's ready for review. I would like to add more doc, but I I'll do that in a future work.

**Review by gautierhattenberger — APPROVED** [review]

**Pull request merged**
