### PR TITLE
Fixed OCaml type inference. Fixed tilt handling

### PR DESCRIPTION
**Pull request by rijesha**
thanks @hendrixgr for pointing out a type inference issue.
Commit also sets the default pan to (90 deg) camera straight pointing down.

### CODE REVIEW

**Comment by rijesha** [comment]
OCaml v3.12 is incompatible with List.iteri.

https://github.com/paparazzi/paparazzi/blob/master/sw/tools/generators/gen_flight_plan.ml#L871

**Comment by gautierhattenberger** [comment]
I don't mind changing the default orientation of the camera, but the other issues seem related to older versions of Ocaml (before 4.x). I don't wont to support them since they correspond to Ubuntu versions that are not supported anymore, hence are not recommended for installation and future developments.

**Comment by rijesha** [comment]
Ok good to know.

**Comment by hendrixgr** [comment]
Hi
I still can't compile it after a clean install with
the multi command installation macro found in the wiki.
Maybe i should unistall paparazzi-dev and reinstall it, i will reply soon.
Chris


make -C /home/hendrix/paparazzi/sw/tools/generators
DEPEND .depend
OL gen_aircraft.ml
OL gen_airframe.ml
OL gen_ubx.ml
OL gen_mtk.ml
OC gen_flight_plan.ml
File "gen_flight_plan.ml", line 871, characters 8-18:
Error: Unbound value List.iteri
make[1]: *** [gen_flight_plan.cmo] Error 2
make: *** [generators] Error 2
hendrix@hendrix-tc4400:~/paparazzi$

**Comment by hendrixgr** [comment]
I unistalled paparazzi-dev and reinstalled it but i get the same error
about "gen_flight_plan.cmo"
Any ideas?

**Comment by hendrixgr** [comment]
" I don't mind changing the default orientation of the camera, but the
other issues seem related to older versions of Ocaml (before 4.x). I don't
wont to support them since they correspond to Ubuntu versions that are not
supported anymore, hence are not recommended for installation and future
developments."
I am locked to Ubuntu 12.04 LTS so is there any way to revert back to the
version i had before?
Chris

**Comment by gautierhattenberger** [comment]
Depending of what you really need, you can either install an older version of Paparazzi (that is supporting Ubuntu 12.04) or try to upgrade Ocaml using OPAM, which should be mostly independent of the system itself.

**Comment by rijesha** [comment]
I tried to install a new version of ocaml with opam but kept running into build problems because all of the packages were for an earlier version of ocaml.
So steps to install ocaml v4.05.0 using opam.

`
sudo apt-get install opam
opam init
opam switch 4.05.0
eval `opam config env`
`
But this doesn't install the required packages. 
opam list only gives the following packages:
`
base-bigarray    base  Bigarray library distributed with the OCaml compiler
base-threads     base  Threads library distributed with the OCaml compiler
base-unix        base  Unix library distributed with the OCaml compiler
`

From this point on will you need to manually install missing packages? 
`
opam install camlp4
opam install ocamlbuild
opam install ocamlfind
opam install xml-light
`
I stopped when my error message was that i was missing ivy.

**Comment by rijesha** [comment]
Sorry about the formatting on the last comment. The problem is with ocamlfind.

> ocamlfind: The META file is missing

So steps until this error:

> sudo apt-get install opam
> opam init
> opam switch 4.05.0
> opam install ocamlfind
> eval `opam config env`

Then perform the make

**Comment by rijesha** [comment]
Well nevermind my last comment. Yes you do need to manually install the packages. 
The wiki is a great source https://wiki.paparazziuav.org/wiki/Installation/FromScratch.

Everything compiles until the GCS.
> File "gcs.ml", line 673, characters 12-36:
> Error: Unbound value Gdk.Window.native_of_xid
> Makefile:85: recipe for target 'gcs.cmo' failed

Steps to install:
> sudo apt-get install opam
> opam init
> opam switch 4.02.3
> opam install ocamlbuild camlp4 ocamlfind conf-gnutls ivy xml-light pcre
> opam install -v lablgtk.2.16.0
> opam pin add lablgtk 2.16.0
> opam install ocamlnet
> eval $(opam config env)

**Comment by rijesha** [comment]
It looks like the following is incorrect:
> opam install -v lablgtk.2.16.0
> opam pin add lablgtk 2.16.0

Instead this works:
> opam pin remove lablgtk
> opam upgrade lablgtk

This sets lablgtk to version 2.18.5.

So final steps to upgrade ocaml are:
> sudo apt-get install opam
> opam init
> opam switch 4.02.3
> opam install ocamlbuild camlp4 ocamlfind conf-gnutls ivy xml-light pcre lablgtk ocamlnet
> eval $(opam config env)

**Pull request merged**
