### PR TITLE
Fix flight plans

### PR DESCRIPTION
**Pull request by Fabien-B**
Remove most of the illegal characters in flight plans.

### CODE REVIEW

**Review by gautierhattenberger — COMMENTED** [review]
what about the deref operator `->` ? It is possible to use the keyword `@DEREF`, but in many cases, it is probably even better to use the macros like `GetPosX`.

**Comment by Fabien-B** [comment]
I Replaced it for most cases I think.
What it seen very often is `stateGetPositionEnu_f()->z`.
The closest macro I found is for rotorcrafts: `#define GetPosAlt() (stateGetPositionEnu_f()->z+state.ned_origin_f.hmsl)`.
Should these occurrences be replaced by this macro ? Won't it change the behavior ? What is `state.ned_origin_f.hmsl` ?

**Comment by gautierhattenberger** [comment]
It is a bad way to have the reference altitude, aka ground alt. So it is probably a good idea to add a macro `GetPosHeight` that juste returns `stateGetPositionEnu_f()->z`

**Comment by Fabien-B** [comment]
I agree, I did that.

**Review by gautierhattenberger — APPROVED** [review]

**Pull request merged**
