### PR TITLE
[no_wind_upload] 

### PR DESCRIPTION
**Pull request by dewagter**
- initial solution was to not send wind unless the (first) airframe firmware was fixedwing
 - alternative could be to check if AT LEAST 1 firmware is fixedwing
 - alternative could be to add a flag to link/server

please vote

### CODE REVIEW

**Comment by flixr** [comment]
Checking available firmwares in the airframe file is simply not robust... and you can already turn of sending of the WIND_INFO message in the misc page of the GCS notebook.
If you want to always disable it for a specific airframe, I suggest to add a define to the GCS section in the airframe file and parse it from the GCS (like e.g. the AC_ICON).

**Comment by dewagter** [comment]
if the GCS can do this in another way, I propose to drop this PR.

**Comment by gautierhattenberger** [comment]
I will add an option to disable it at startup anyway, I think it is missing.

**Comment by dewagter** [comment]
that is great, thanks a lot

-Christophe

**Comment by flixr** [comment]
You mean to disable it for all aircrafts?

Am 04.11.2016 11:22 vorm. schrieb "Christophe De Wagter" <
notifications@github.com>:

> that is great, thanks a lot
>
> -Christophe
>
> On Fri, Nov 4, 2016 at 11:17 AM, Gautier Hattenberger <

**Pull request closed without merging**
