### PR TITLE
Nmea fix

### PR DESCRIPTION
**Pull request by dewagter**

### CODE REVIEW

**Comment by dewagter** [comment]
Any reason not to know anything about GPS while no position information is available?

**Comment by dewagter** [comment]
mostly solved by https://github.com/paparazzi/paparazzi/issues/1617

 - [x] gps_nmea.stat
 - [ ] typo in secondary
 - [ ] no info(e.g.TOW/SVINFO) while no position on bebop

**Comment by flixr** [comment]
I think instead of checking for `gps_nmea.pos_available` we should check if a new valid sentence is available

**Comment by flixr** [comment]
@dewagter see alternative proposal/fix in #1619

**Pull request closed without merging**
