### PR TITLE
[flightplan] add pre and post calls at stage level

### PR DESCRIPTION
**Pull request by gautierhattenberger**
this can help for issues like #1882

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
Should I merge this already ?

There is still something not consistent with the current generator when the `until` attribute is used. Some instructions are checking the condition at the beginning (like a `while` loop), while others are testing it after calling nav functions (like a `do ... while` loop). I didn't change the behavior for now. But what would be the best choice ?

**Comment by flixr** [comment]
I don't quite understand what this has to do with the `until` attribute, can you elaborate (e.g with some examples)?

**Comment by gautierhattenberger** [comment]
If you have `<attitude ... until="some_condition"/>`, it will generate
```
if (some_condition) NextStageAndBreak();
NavAttitude(...)
break;
```
But if you do `<circle ... until="some_condition"/>`, you will have
```
NavCircle(...)
if (some_condition) NextStageAndBreak();
break;
```
So, in the first case, if the condition is not true, the nav instruction will not be called, while with the second case, nav instructions are called at least once before changing stage.
This is indeed not related to the current issue, but I just realized it, so I'm wondering if something should be done for this.
For the first case, `heading`, `attitude`, `manual` are concerned. For the second, it's `go`, `stay`, `circle`, `eight`, `oval` and `survey`.

**Comment by flixr** [comment]
Ok. Then I would say we merge this as it is... and make a new issue/PR for consistent `until` usage...

**Pull request merged**
