### PR TITLE
[pprz center] improve handling of programs from control_panel.xml

### PR DESCRIPTION
**Pull request by flixr**
Add possibility to launch global commands from tools menu.
Prefixing a program command in control_panel.xml with `$` will strip the `$` and then execute the command.

This makes it possible to start programs without knowing their absolute path.
Already used to start a simple http server from python.

Also parse the args from the programs section of control_panel.xml when starting them from the tools menu.
This makes it possible to specify default args.

### CODE REVIEW

**Comment by flixr** [comment]
Hm... only one problem: if you save the session like this, it saves the args separately and adds them twice upon starting the session again.
But specifying the args in program doesn't seem to work..

**Comment by gautierhattenberger** [comment]
I'm not sure their is an other choice than making a local script that set the default options

**Comment by flixr** [comment]
Updated, now you can specify args in the programs section and they are actually used when starting from the tools menu...

**Comment by gautierhattenberger** [comment]
tested and working

**Pull request merged**
