### PR TITLE
[gps] Move GPS relative position to ABI message

### PR DESCRIPTION
**Pull request by fvantienen**
Add the option for multiple relative position messages from the GPS. This moves the communication to relative position to ABI messages

### CODE REVIEW

**Comment by fvantienen** [comment]
Needs a pprzlink update first

**Comment by gautierhattenberger** [comment]
I agree with this. It just need to fix the conflicts after #3409. However I don't see the changes for pprzlink in a PR ?

**Comment by fvantienen** [comment]
> I agree with this. It just need to fix the conflicts after #3409. However I don't see the changes for pprzlink in a PR ?

I made a PR for the pprzlink, and already fixed the merge conflicts with the new master.

**Review by gautierhattenberger — DISMISSED** [review]
Can be merged after updating pprzlink ref (corresponding PR is merged)

**Comment by fvantienen** [comment]
Updated pprzlink ref

**Review by gautierhattenberger — APPROVED** [review]

**Pull request merged**
