### PR TITLE
Full reatured fixedwing example for Pixracer AP board

### PR DESCRIPTION
**Pull request by OpenUAS**
Still needs quite some testflights. Weather permitting tests this weekend. If it works as expected a pull request honoring after that.

### CODE REVIEW

**Comment by podhrmic** [comment]
@OpenUAS any news here? Has it been tested and flown?

**Comment by OpenUAS** [comment]
Yes, test flown Auto2 on "classic" control, but not tuned ETECS yet. The next week test and merge. ad to still get a good V (I Works) reading on analog, but sensor was not working.
Will then  update AC with Dynamic mag compensation and tuned and flown on ETECS. Maybe even a small video if time permits.

**Comment by OpenUAS** [comment]
100% auto test-flight performed. Could use more testing... as always ;-)

**Comment by gautierhattenberger** [comment]
right, conf and control_panel shouldn't be under revision control. It seems this is a bit messy with a lot of unwanted changes.

**Pull request merged**
