### PR TITLE
update PnP:

### PR DESCRIPTION
**Pull request by dewagter**
-  reference to paper
 -  initialize
 - fix uninvertible problem

### CODE REVIEW

**Comment by dewagter** [comment]
@guidoAI

**Comment by gautierhattenberger** [comment]
does it needs to be completed or is it ready to merge ?

**Comment by dewagter** [comment]
- rebased on master
 - updated code based on change in https://github.com/paparazzi/paparazzi/pull/2339

**Comment by dewagter** [comment]
Ready

**Pull request merged**
