### PR TITLE
[datalink] Set Xbee channel

### PR DESCRIPTION
**Pull request by Fabien-B**
Configure the xbee channel at modem initialization.
Use option -ch to change xbee channel.
Default is 0x0C.

### CODE REVIEW

**Comment by dewagter** [comment]
Will it change the channel of the XBee if no option is given?

**Comment by dewagter** [comment]
Great, thanks!

PS: what is the corresponding define to add to your airframe to change the airborne side?

**Comment by Fabien-B** [comment]
In one of my airframes I have this line:
`<define name="XBEE_INIT" value="\"ATID3332\rATCH17\rATP1\rATBD6\r\""/>`
But I think this only necessary stuff is :
`<define name="XBEE_INIT" value="\"ATCH17\r\""/>`
I may add a tag to the telemetry configuration to make ot easier.

**Comment by dewagter** [comment]
Thanks. Looks great. Info in config xml is also a good idea.

**Comment by gautierhattenberger** [comment]
will merge after testing on hardware

**Comment by Fabien-B** [comment]
Tested on hardware, it works !
The tests I made :
Aircraft on channel 0x10, modem on channel 0x0C:
    launched without arguments : not working (as expected)
    launched with arg _-ch 0x10_ : it works
Modem also on channel 0x10 , launched without argument : it works (so it don't change the channel if the argument is not given)

**Pull request merged**
