### PR TITLE
MAVLab course update: typos, comments (tudelft pr#64)

### PR DESCRIPTION
**Pull request by dewagter**
Import PR from https://github.com/tudelft/paparazzi/pull/64
@matteobarbera

### CODE REVIEW

**Comment by matteobarbera** [comment]
@dewagter the build fails while in the pre-install phase, `sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y` and `sudo apt-get install -y --force-yes paparazzi-dev paparazzi-jsbsim gcc-arm-embedded gcc-arm-linux-gnueabi g++-arm-linux-gnueabi libipc-run-perl rustc cargo libgazebo9-dev libgps-dev`. Is this a Travis issue? I can't recreate it locally, and I see #2592 had a similar issue in one of the earlier commits

**Comment by dewagter** [comment]
Build error seems quite unrelated to the commits.

Is being addressed in https://github.com/paparazzi/paparazzi/issues/2594

**Comment by dewagter** [comment]
@matteobarbera 
Can you pay special attention to the ```waypoint_set_``` functions which were  ```waypoint_move_``` functions in the tudelft branch.

**Comment by matteobarbera** [comment]
The mavlabCourse2019 branch in the tudelft repo does not have the `waypoint_move_here_2d` function defined, it's lagging behind paparazzi/master by a lot of commits

**Comment by gautierhattenberger** [comment]
can you rebase on top of master to get #2594 changes ?

**Comment by matteobarbera** [comment]
I've changed the `waypoint_set_here_2d` function with the more recent ones, and rebased to get the travis changes, but I can't edit the pull request directly. https://github.com/matteobarbera/paparazzi/tree/matteobarbera/update_course_rebase

**Review by gautierhattenberger — APPROVED** [review]

**Pull request merged**
