### PR TITLE
Sdlog

### PR DESCRIPTION
**Pull request by philipan**
add/improve sdlog feature for apogee-barometer, temp_temod, humid_sht and airspeed_ets

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
I think it is fine for merging. @philipan do you know that if you need to log from several sensors at the same time, you can use the flight recorder module: http://wiki.paparazziuav.org/wiki/Apogee/v1.00#On-board_Data_Logging
With this data are written in a separated file in binary format and can be extracted later to produce a standard paparazzi log file (like the one produced by the ground station).

**Comment by philipan** [comment]
Thx, yes I knew about the Flight Recorder. I use it always additionally to the pure meteo data sdlog files (for some reason I wasn't able to replay the decoded FR-log file in pprz, but I will look into this again the next weeks ...).

**Comment by philipan** [comment]
Please wait with merging. I've seen that baro logs data only once and not continously. Have to figure out ...

**Comment by gautierhattenberger** [comment]
@philipan Any updates ?

**Comment by philipan** [comment]
Hi,

I think it is ready for merging now, although I could not test the very 
last version on the hardware (compiling works). May be I will be able to 
test it tomorrow on the hardware.

Am 24.02.2016 um 11:07 schrieb Gautier Hattenberger:
>
> @philipan <https://github.com/philipan> Any updates ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/paparazzi/paparazzi/pull/1512#issuecomment-188173891>.
>

-- 
--------------------------------------
PD Dr. Andreas Philipp
Institute of Geography
University of Augsburg
Universitaetsstrasse 10
D - 86135 Augsburg
Germany

Phone:  ++49/821/598-2266
Fax:    ++49/821/598-2264
Email:  a.philipp@geo.uni-augsburg.de
http://www.geo.uni-augsburg.de/lehrstuehle/phygeo/personal/philipp/
--------------------------------------

**Comment by philipan** [comment]
Tested now on hardware. Works fine and is ready for merging.

**Pull request merged**
