### PR TITLE
Optic flow changes

### PR DESCRIPTION
**Pull request by manoskyr**
This pull request tries to make the Lucas-Kanade optical flow algorithm more robust and extentable by keeping track of the same features over time instead of re-detecting every frame. Re-detection will now happen when tracked corners reach a low threshold, and only in the region(s) that have a low amount of corners.
It also fixes the already existing method which detected corners on the new frame and then projected them to the previous one to track them again.
The second commit introduces an FPS parameter to all computer vision modules such that the video listeners that they attach to the camera with the `cv_add_to_device` function can operate at a lower frequency than the camera frame rate. This can be useful in cases like the optical flow where a high frame rate could accumulate error. Note that many of those modules could not be compiled out of the box, but the feature was added so that the call to the `cv_add_to_device` would not be a source of error later on.

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
I can't really evaluate the optical flow part, but adding FPS parameter is definitely a good idea.

**Comment by ETitus** [comment]
@gautierhattenberger 
I recently pulled master and got presented some warnings in the optical flow code. To test I cloned a fresh master, selected the TU Delft Conf and ARDrone2_opticflow.


The following errors weren't there before this pull request. I am not sure what the effect of these warnings is. As for the shadowing of the global state, that seems strange as it was called state before this pull request. However it might be a good idea to rename that.
As for the discard const qualifier, it seems the casting isn't entirely correct? I am not sure however.

> modules/computer_vision/opticflow/opticflow_calculator.c: In function 'calc_fast9_lukas_kanade':
modules/computer_vision/opticflow/opticflow_calculator.c:256:87: warning: declaration of 'state' shadows a global declaration [-Wshadow]
 void calc_fast9_lukas_kanade(struct opticflow_t *opticflow, struct opticflow_state_t *state, struct image_t *img,
                                                                                       ^
In file included from modules/computer_vision/lib/vision/image.h:32:0,
                 from modules/computer_vision/opticflow/opticflow_calculator.h:37,
                 from modules/computer_vision/opticflow/opticflow_calculator.c:37:
/home/titus/test/paparazzi/sw/airborne/state.h:449:21: note: shadowed declaration is here
 extern struct State state;
                     ^
modules/computer_vision/opticflow/opticflow_calculator.c: In function 'calc_edgeflow_tot':
modules/computer_vision/opticflow/opticflow_calculator.c:519:81: warning: declaration of 'state' shadows a global declaration [-Wshadow]
 void calc_edgeflow_tot(struct opticflow_t *opticflow, struct opticflow_state_t *state, struct image_t *img,
                                                                                 ^
In file included from modules/computer_vision/lib/vision/image.h:32:0,
                 from modules/computer_vision/opticflow/opticflow_calculator.h:37,
                 from modules/computer_vision/opticflow/opticflow_calculator.c:37:
/home/titus/test/paparazzi/sw/airborne/state.h:449:21: note: shadowed declaration is here
 extern struct State state;
                     ^
modules/computer_vision/opticflow/opticflow_calculator.c: In function 'opticflow_calc_frame':
modules/computer_vision/opticflow/opticflow_calculator.c:689:84: warning: declaration of 'state' shadows a global declaration [-Wshadow]
 void opticflow_calc_frame(struct opticflow_t *opticflow, struct opticflow_state_t *state, struct image_t *img,
                                                                                    ^
In file included from modules/computer_vision/lib/vision/image.h:32:0,
                 from modules/computer_vision/opticflow/opticflow_calculator.h:37,
                 from modules/computer_vision/opticflow/opticflow_calculator.c:37:
/home/titus/test/paparazzi/sw/airborne/state.h:449:21: note: shadowed declaration is here
 extern struct State state;
                     ^
modules/computer_vision/opticflow/opticflow_calculator.c: In function 'cmp_array':
modules/computer_vision/opticflow/opticflow_calculator.c:858:25: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
   const uint16_t *pa = *(const uint16_t **)a;
                         ^
modules/computer_vision/opticflow/opticflow_calculator.c:859:25: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
   const uint16_t *pb = *(const uint16_t **)b;
                         ^


@manoskyr Did you happen to test it on an ARDrone2 also? Otherwise I will do that next week.

**Comment by gautierhattenberger** [comment]
This will be solved when merging https://github.com/paparazzi/paparazzi/pull/2087 (which should happen soon)

**Comment by ETitus** [comment]
I noticed that the "state" shadow declaration has been fixed indeed by @kirkscheper #2087, but the other one hasn't been fixed yet:

> modules/computer_vision/opticflow/opticflow_calculator.c:858:25:
> 
>  warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
>    const uint16_t *pa = *(const uint16_t **)a;
>                          ^
> modules/computer_vision/opticflow/opticflow_calculator.c:859:25: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
>    const uint16_t *pb = *(const uint16_t **)b;
>                         ^

```
static int cmp_flow(const void *a, const void *b)
{
  const struct flow_t *a_p = (const struct flow_t *)a;
  const struct flow_t *b_p = (const struct flow_t *)b;
  return (a_p->flow_x * a_p->flow_x + a_p->flow_y * a_p->flow_y) - (b_p->flow_x * b_p->flow_x + b_p->flow_y *
         b_p->flow_y);
}

/**
 * Compare the rows of an integer (uint16_t) 2D array based on the first column.
 * Used for sorting.
 * @param[in] *a The first row (should be *uint16_t)
 * @param[in] *b The second flow vector (should be *uint16_t)
 * @return Negative if a[0] < b[0],0 if a[0] == b[0] and positive if a[0] > b[0]
 */
static int cmp_array(const void *a, const void *b)
{
  const uint16_t *pa = *(const uint16_t **)a;
  const uint16_t *pb = *(const uint16_t **)b;
  return pa[0] - pb[0];
}
```

Comparing these two functions I noticed that cmp_array implemented different usages of *. I am not sure what is done exactly, but the error disappears when you match the *'s with the cmp_flow function

**Pull request merged**
