### PR TITLE
MPU based IMUs: default scaling based on selected range

### PR DESCRIPTION
**Pull request by flixr**
Set default gyro/accel sensitivity based on selected range.

### CODE REVIEW

**Comment by flixr** [comment]
This is not finished yet... and I'm unsure which approach is nicer:
- have one common default file like the `imu_mpu60x0_defaults.h`
- set the defaults in the header file for each IMU "implementation" (like e.g. for apogee and px4fmu)

The difference being that if we use a common defaults file, the range defines need to have the same name and it might not be consistent with the defines for the other IMU parameters anymore... but we have more duplication.

**Comment by gautierhattenberger** [comment]
I would be more in favor of each IMU having its own definitions. If we finally manage to not rely anymore on the global imu struct (among other things) it will be easier to run several IMU at the same time and then it can be annoying to configure them with the same variables.

**Comment by flixr** [comment]
Ok, done for MPU60X0...
When using multiple IMUs, the issue is actually not the global IMU struct anymore, but rather the scaling defines (if the IMU driver doesn't have it's own scaling implementation and uses the one from imu.c)...

**Comment by flixr** [comment]
Ok, didn't remember correctly... the global IMU struct is still an issue, see #1585

**Comment by flixr** [comment]
Anyway, this looks to merge for me (once it was tested).

**Comment by EwoudSmeur** [comment]
Works on apogee with 16g and 2000deg/s scaling!

**Pull request merged**
