### PR TITLE
Master cleanup of deprecated parts

### PR DESCRIPTION
**Pull request by fvantienen**
Based on the meeting I removed some deprecated parts of Paparazzi.
Related to #1214

This removes:
- ardrone2_sdk board and associated subsystems
- vision submodule

And renames the ardrone2_raw board and airframe file to simply ardrone2

### CODE REVIEW

**Comment by flixr** [comment]
do you want to keep paparazzi_raw as type in the python scripts or simply rename it to paparazzi?

**Comment by gautierhattenberger** [comment]
I think `paparazzi` makes more sense now

**Comment by dewagter** [comment]
you mean: ardrone?

-Christophe

**Comment by gautierhattenberger** [comment]
no, it is the name of the "firmware" we run in Parrot drones, so either "native" or "paparazzi"

**Comment by flixr** [comment]
@fvantienen could you make the changes and rename the `paparazzi_raw` firmware name to `paparazzi`?

**Comment by fvantienen** [comment]
Done ;)

**Comment by flixr** [comment]
Um, we still have `sw/ext/bebop.py`? Shouldn't we rather use only `sw/tools/parrot/bebop.py`?
Also do you want to keep the `raw` folder?

**Comment by flixr** [comment]
I guess we can also remove the AHRS_ARDRONE2 message?

**Pull request merged**
