### PR TITLE
[pkg_man] mini package manager

### PR DESCRIPTION
**Pull request by dewagter**
store where files are copy-pasted from so they can benefit from downstream and update upstream

### CODE REVIEW

**Comment by flixr** [comment]
This is only meant to more easily update files that are copied and committed to the paparazzi tree, right?

**Comment by podhrmic** [comment]
If it is for beebop only (judging from the comments?) shouldn't it be in `sw/tools` ?

**Comment by dewagter** [comment]
@flixr yes, but most of all: to store where it came from, which revision etc
@podhrmic  not for bebop (will fix comments) but for small "partial submodules"

**Comment by flixr** [comment]
LGTM

**Comment by dewagter** [comment]
Any suggestion in which folder to put pkgman imported code? Can it be all
over the place like now should they all go in sw/ext or in sw/pkgman to
differentiate with submodules?

**Comment by flixr** [comment]
Does it need to be put in a specific standard directory? It might make more sense to choose the directory based on what is copied...

**Pull request merged**
