### PR TITLE
Speech recognition to jump to a block

### PR DESCRIPTION
**Pull request by rmeertens**
Maybe not the best pull request ever, but I played around with speech recognition last weekend. 
I added one simple python example for jumping to a new block, and one example on how to do this with speech recognition (although a certain python library is needed). 

If anybody likes the idea of a speech controlled airplane, let me know!

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
At least it would be nice to factorize the jump_to_block code and provide some information on which library to install to make this running

**Comment by rmeertens** [comment]
Can and will do!

**Comment by flixr** [comment]
Should also use 4 spaces for indentation of the python code and be moved to pprzlink...

And I don't know about any python interpreter for the flight plan... what exactly were you thinking about?

**Comment by rmeertens** [comment]
Will do. 
As for the python interpreter: currently I have commands that say "Go to block 4"... which works. But I would like to say things like: "Go to waypoint 'river'". Or: "execute block 'land here'".

**Comment by flixr** [comment]
AFAIK there is nothing like that yet...

**Comment by OpenUAS** [comment]
A fun thing the idea of a speech controlled airplane, although for my no telemetry flights I need a mike in my plane and a megaphone ;), Anyhow... adding something like select AC "ac name" or ID for multi UAS flights. Also a conformation feedback [Really do XYZ? Yes, No?] makes it a bit less adventurous :) Also with multiple people having a say does not always end well ... http://vignette3.wikia.nocookie.net/smurfs/images/4/4c/Weather_Smurfing_Machine_Comic.jpg

**Comment by flixr** [comment]
@rmeertens should we keep this open? If it only depends on pprzlink, it should go in a tools/examples dir there...

**Comment by rmeertens** [comment]
Close it for now, don't know if anybody is interested at all in having a speech controlled autopilot ;)

**Pull request closed without merging**
