### PR TITLE
Config files cleanup

### PR DESCRIPTION
**Pull request by podhrmic**
Config files moved from the `conf` folder back to the airframe folder, so the user directories wont clutter the `conf` folder any more.

### CODE REVIEW

**Comment by podhrmic** [comment]
Related to #1503

**Comment by flixr** [comment]
:+1: from me, @OpenUAS as you originally moved them you might want to comment/object now ;-)

**Comment by dewagter** [comment]
To have all conf in between the makefiles and messages.xml is not very nice, so for me this change is OK.

If having conf mixed with airframes is not desired I could also image that config files would reside in a special folder like ./conf/personal or ./conf/conf or ./conf/config/

**Comment by podhrmic** [comment]
So far 3 agree.
@gautierhattenberger @OpenUAS any objections to the change?

**Comment by gautierhattenberger** [comment]
Having personal conf in airframes directory is probably not ideal but still okay with the current configuration structure. So I'm fine with this.

**Comment by flixr** [comment]
We could also put the personal confs in a folder like @podhrmic and @dewagter already suggested.
Either way I'm fine with it....

If @OpenUAS doesn't object until tonight, I'll merge it....

**Comment by podhrmic** [comment]
@flixr merge then?

**Pull request merged**
