### PR TITLE
[paparazzi center] add copy A/C menu entry

### PR DESCRIPTION
**Pull request by flixr**
Start to solve #1209

Does not yet ask for a new airframe file name and copy the airframe file.

### CODE REVIEW

**Comment by flixr** [comment]
There doesn't seem to be an OCaml function to copy a file....?

**Comment by dewagter** [comment]
Nice feature! Use this very often.

**Comment by gautierhattenberger** [comment]
It doesn't seems to exist. Here is an example on how to make it by hand: https://ocaml.github.io/ocamlunix/ocamlunix.html#sec33

**Comment by flixr** [comment]
Yeah, but further up in `write_conf_xml` we already use
```Sys.command (sprintf "cp %s %s"  Utils.conf_xml_file Utils.backup_xml_file)```
, so I guess we can just do the same for this here... although this is not so nice in terms of portability...

**Comment by gautierhattenberger** [comment]
indeed...

**Comment by gautierhattenberger** [comment]
If someone can test this before merging

**Comment by dewagter** [comment]
Just tested: works fine for my.

(although the first time my cursor could not be seen and I could not type in the airframe.xml selection dialog, but since I can not reproduce this anymore.)

**Comment by flixr** [comment]
Works nicely for me. Thanks @gautierhattenberger for fixing the warning and adding the copy of the airframe file.

**Pull request merged**
