### PR TITLE
STM32 I2C driver fix

### PR DESCRIPTION
**Pull request by softsr**
Improves stability in case of the bus stuck.

### CODE REVIEW

**Comment by softsr** [comment]
How can it be that the code compiles on the computer but gives errors with the the tests?

**Comment by gautierhattenberger** [comment]
you have defined `WD_DELAY` somewhere, probably the header, but didn't commit it

**Comment by softsr** [comment]
The WD_DELAY defined in the same file:
https://github.com/softsr/paparazzi/blob/stm32_i2c_fix/sw/airborne/arch/stm32/mcu_periph/i2c_arch.c#L1301

**Comment by gautierhattenberger** [comment]
true, I thought it was a new variable, that's why I didn't see it in the diff

**Comment by softsr** [comment]
What could be done in this case?

**Comment by gautierhattenberger** [comment]
No idea, it is compiling on my laptop. I just restarted the CI to see.

**Comment by flixr** [comment]
You have `WD_DELAY` defined inside a `#if USE_I2C1 || USE_I2C2 || USE_I2C3` block.
So if you don't have one of those enabled, compilation will fail.

Can you please also run the file through the code style fixer?
`./fix_code_style.sh sw/airborne/arch/stm32/mcu_periph/i2c_arch.c`

**Comment by softsr** [comment]
But what it then wrong with having it inside? It will be defined if using any of the I2C peripherals.

**Comment by flixr** [comment]
Because the i2c code is compiled by default, even if you then don't have any devices actually using it...

**Comment by flixr** [comment]
@gautierhattenberger did you test this?
I'm not able to test this right now, shall we merge it as is or does it need more testing?

**Comment by podhrmic** [comment]
I ll test it today, please don't merge without testing.

**Comment by softsr** [comment]
Any kind of tests or feedback are very appreciated.

**Comment by OpenUAS** [comment]
If Merged I can test with some I2C devices, no timeframe guarantee sadly (weather etc permitting) most likely the Eagletree airspeed sensor first

**Comment by softsr** [comment]
I tested it with the hmc5883 sensor, but would be very important to check if the eagletree airspeed sensor work correctly.

**Comment by podhrmic** [comment]
I tested it on Lisa MX and tried to abuse the bus really hard, but it always recovered. Recommended for merge.

**Comment by flixr** [comment]
Great, thx guys!

**Comment by flixr** [comment]
Also see #1268 for better error reports...

**Comment by OpenUAS** [comment]
+1: Super, time to un-dust some of our eagletree sensors and find an airframe to test on.

**Pull request closed without merging**
