### PR TITLE
[submodule] update eigen ref and version

### PR DESCRIPTION
**Pull request by gautierhattenberger**
now hosted on Gitlab, latest version: 3.3.9

it is also fixing some deprecated functions

### CODE REVIEW

**Comment by noether** [comment]
Have you checked whether the kalman filter that guys wrote works? just in case.

I will also test the GVF_parametric with this new Eigen version. If it does not work, I would say it will be during the compiling stage.

I will check it in two or three days :P. Thanks.

**Comment by gautierhattenberger** [comment]
Actually I had to update eigen to make our code compile without `deprecated` warnings... and it is still working :)

**Comment by noether** [comment]
Haha, good. I remember that I had to deactivate one warning for the same reason. I will check the branch asap, and modify the GVF if needed. I will let you know it.

Thanks

**Comment by noether** [comment]
The gvf compiles perfectly here with this Eigen lib.

Thanks for the update :P.

**Review by noether — APPROVED** [review]

**Pull request merged**
