### PR TITLE
[misc] Add GPSD to IVY functionalities for follow me

### PR DESCRIPTION
**Pull request by fvantienen**

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
For some reason that I have forgotten, the gpsd2ivy (and dependency to gpsd lib) was not mandatory on purpose. I think it was a request from @martinmm but I can't remember why. It can be because gpsd daemon can be in conflict with other things in some cases, so not everyone wants to install it.

**Comment by fvantienen** [comment]
Ok I can remove the automatic build of it, or maybe add a check if it is installed and then only build it.

**Comment by gautierhattenberger** [comment]
checking before compiling seems a good idea

**Comment by fvantienen** [comment]
I now added a check before compilation

**Comment by gautierhattenberger** [comment]
seems travis build is fine, but report to github failed: https://travis-ci.org/github/paparazzi/paparazzi/builds/663048143

**Pull request merged**
