### PR TITLE
[link] Pprzlink router (for herelink)

### PR DESCRIPTION
**Pull request by fvantienen**
This is a simple pprzlink router for the Herelink, without any crc checking or parsing. There is no real manual yet, but only some adb commands which needs to be executed on the Air and Ground module.

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
The code itself looks fine, eventually you could format it with paparazzi rules.
The only thing is maybe the folder name `link` which is very generic. Could you find something a bit more specific, eventually `herelink` and add a small readme at least to tell what it is suppose to be.

**Comment by fvantienen** [comment]
I will add some more information later. But I made it for the herelink, but can be used more general. It is just a simple forwarder between UART and UDP endpoints.

**Comment by gautierhattenberger** [comment]
This is what I understood, but the name can be misleading with the actual link agent. Maybe a name with "bridge-something" ?

**Review by gautierhattenberger — DISMISSED** [review]
Except renaming it to something more explicit than pprz_router, I think it is fine

**Comment by OpenUAS** [comment]
@fvantienen plz, rename to something so it can be merged?... and I can test on a separate herelink set I have at hand.

**Comment by gautierhattenberger** [comment]
@fvantienen can you address the naming issue before next release ? Thanks

**Comment by fvantienen** [comment]
What would you prefer as name @gautierhattenberger , as I cannot think of any other correct name?

**Comment by Fabien-B** [comment]
`bridge_udp_uart` ?

**Comment by gautierhattenberger** [comment]
I'm also fine with bridge_udp-uart or udp-uart_bridge, as you like it

**Comment by gautierhattenberger** [comment]
@fvantienen can you make the required changes ? I want to make the 5.18 release next week. Thanks

**Comment by gautierhattenberger** [comment]
@fvantienen can you update or close this if not relevant anymore ?

**Comment by dewagter** [comment]
Hi @gautierhattenberger and @Fabien-B,

The current naming is in line with the other names like ```/etc/mavlink-router``` on the herelink and can be also be used from ```UDP``` to ```UDP``` or any other combination. In this sense it is more a router than an uart-udp_brigde.

On top of that, this code is already widely distributed and documented on several wiki. Any possibility to keep this name?

**Review by gautierhattenberger — APPROVED** [review]
lets keep it like this then

**Pull request merged**
