### PR TITLE
[airframes] use standard motor mixing types for some quads

### PR DESCRIPTION
**Pull request by flixr**
This will change the effect of the gains (depending on the type), but should be finally correct.
Especially the yaw commands have about half the effect now...

Needs testing on ardrone and bebop, and probably some adjustment of the gains.

### CODE REVIEW

**Comment by flixr** [comment]
@gautierhattenberger @kevindehecker @fvantienen @EwoudSmeur 
Would be great if you guys could test the updated ardrone and bebop airframe files.
Btw, I was wondering anyhow that none of those have an integral term set...

Also the ardrone2_optitrack.xml (which I didn't change here) has different gains, which I don't quite understand as it is the same controller and airframe.

**Comment by gautierhattenberger** [comment]
Tested and it seems to be working as expected

**Comment by flixr** [comment]
You tested both ardrone2 and bebop?
The behaviour (with these updated gains and mixing) seems to be the same as before?

**Comment by kevindehecker** [comment]
I tested ARDrone2 in ATT and NAV mode with the indi airframe file, which seems to work.

**Comment by flixr** [comment]
The question is if the updated gains match the new motor mixing scaling.
Since INDI does not use these gains, it needs to be tested with the "classic" controllers....

Also I'm still curious on why neither ardrone2 nor bebop have any igains set...
Neither why the optitrack airframe uses different gains...

**Comment by gautierhattenberger** [comment]
I tested both, it looks the same. I just don't like some of the parameters for the ardrone2 (max yaw rate, gains a bit higher than what I'm used to). Otherwise it is flyable like this. Only did ATT so far.

**Comment by EwoudSmeur** [comment]
It does also matter for the INDI controller, as the actuator effectiveness is sqrt(2) lower... Though Kevin was not flying with INDI but with quat_int

**Comment by flixr** [comment]
Yes, but the indi airframe was not changed in this PR... And the question
was specifically if the updated gains match the mixing...
Am 22.07.2015 11:06 schrieb "Ewoud Smeur" <notifications@github.com>:

**Comment by flixr** [comment]
Ups, sorry... I did change the ardrone indi airframe... Wanted to omit that one first...

**Comment by kevindehecker** [comment]
But now I actually have flown with adaptive indi, and it works great! 

And as @EwoudSmeur mentioned, apparently I flied with standard stuff op to now, and that also seems to work. (in both cases for ARDrone2 in optitrack enviroment that is)

**Comment by flixr** [comment]
And what is up with the optitrack airframe and it's totally different gains?

**Comment by kevindehecker** [comment]
That I don't know. I use the standard indi gains with the optitrack systen, except for the h&v P and D guidance gains, which I have set much higher since there is perfect gps. Using those I get almost no position error, and pretty stable flight otherwise.

**Comment by flixr** [comment]
Could you please discuss this with @fvantienen, you guys are the only ones using optitrack, if the ardrone2_optitrack.xml airframe file is outdated, then plz update it to what you are using...
If it is not used at all, plz remove it...

**Comment by kevindehecker** [comment]
@fvantienen I think my setup for optitrack runs pretty smooth by now. So, how about taking this one #1257 ?

**Pull request merged**
