### PR TITLE
refactor attitude reference

### PR DESCRIPTION
**Pull request by flixr**
Attitude reference generation implementations have no global vars themselves anymore...

### CODE REVIEW

**Comment by flixr** [comment]
@gautierhattenberger @EwoudSmeur any comments on this?

**Comment by EwoudSmeur** [comment]
I like that you can turn the attitude reference off!

**Comment by flixr** [comment]
That part is actually exactly the same as before...

**Comment by flixr** [comment]
So the main idea here was to implement the ref models as sort of "library" functions, where there are no global vars needed by other parts declared in the ref model code.
E.g. before indi also compiled stabilization_attitude_ref_quat_int.c, but all it needed/used from that was the `stab_att_sp_quat` without ever actually running the ref model.

On the potential flip-side of this is that there are no pure "interface" functions like `stabilization_attitude_ref_update` anymore that are shared across all implementations.
Instead you have to choose if/which ref model you use directly in the stabilization algo.

In general I would like to see more changes like this, meaning putting more things in structs and passing those as arguments to the functions instead of relying on global vars.
This also makes it a lot easier to use/test these functions in other contexts, like e.g. run different ref models for comparison and call them from python code, etc...

**Comment by gautierhattenberger** [comment]
I didn't test it yet, but on the general idea it is fine for me

**Pull request merged**
