### PR TITLE
replace subsystem by module in all airframes

### PR DESCRIPTION
**Pull request by flixr**
Towards making it easier to actually convert more subsystems to module...

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
any idea to merge `modules` section into the correct `firmware` section (except by hand) ?

**Comment by podhrmic** [comment]
This might sound like a stupid question, but why do we want to change everything to modules? It kind of make sense to have some subsystems that do certain things, and modules that are sort of "smaller subsystems"? Improving subsystems etc yes, but everything as a module seems to be confusing? Just making sure we are on the same page...

**Comment by gautierhattenberger** [comment]
For now, modules are only used as "super" makefile with embedded documentation and settings. The internal static scheduling is the same as before (and will probably stay like this for some time).
So the produced code is the same as before.

Now, regarding the explicit distinction of subsystem and modules in the airframe, I don't think it is really helping new users:
- it is not obvious why you have to different ways to configure things
- some elements like INS, IMU or GPS exist as modules and subsystems
- configuration files are in many different places (modules, firmware shared/FW/RC)

Also, we are planning to implement a dependency mechanism that allow to automatically load required modules, detect some inconsistent configurations, allow shorter firmware section with meta-modules, load modules in correct order and so on. All this things are much easier when you work with the same type of element.
Again, the internal code will stay the same as long as the modules description doesn't allow to produce a code with a precise scheduling if needed (like current subsystems, in some cases at least).

**Comment by flixr** [comment]
@podhrmic see https://github.com/paparazzi/paparazzi/issues/1475 for the main issue tracking/explaining subsystem->module conversion

**Comment by flixr** [comment]
@gautierhattenberger I don't have a good idea on how to merge the modules section automatically...

**Comment by flixr** [comment]
From my side this is good to merge...

**Comment by gautierhattenberger** [comment]
I guess everyone will need to update their files manually for the last part.
Let's merge this then.

**Pull request merged**
