### PR TITLE
Aiframe cleanup

### PR DESCRIPTION
**Pull request by podhrmic**
unused airframe xml files fronm conf_example and conf_test.xml were moved to obselete folder, see #1236 for more info.

### CODE REVIEW

**Comment by flixr** [comment]
Should we really call the folder `obsolete`? Maybe we can find a better name...
Could you plz also update the conf_tests.xml?

**Comment by OpenUAS** [comment]
I vote for untested, gives less of expectancy for the outcome of using these airframes.

**Comment by podhrmic** [comment]
Changed the name to "untested". Also the conf_tests.xml is updated.

**Comment by flixr** [comment]
One more thing that we should probably consider:
while these airframes are untested (in the sense that they are not part of the example or test conf), most of them should still work just fine.
But since they are moved one directory level lower now all of their relative paths to the airframe.dtd will be wrong.
Maybe it would make more sense to make the directory structure rather flat and similar between `examples` and `untested`, i.e.:
```
conf/airframes
   |
   |---- examples
   |    |
   |    |---- foo.xml
   |    |---- bar.xml
   |
   |---- untested
   |    |
   |    |---- baz.xml 
```

Then we could also more easily move a file from examples to untested and vice versa...

**Comment by podhrmic** [comment]
I already did that.

**Comment by flixr** [comment]
@podhrmic Uhm... no...
e.g. `conf/airframes/examples/beagle_bone_black.xml` was renamed to `conf/airframes/untested/examples/beagle_bone_black.xml` without changes...
So adding another directory level...

**Comment by podhrmic** [comment]
yes, so then you can move it from ``conf/airframes/untested/examples/beagle_bone_black.xml`` to ``conf/airframes/examples/beagle_bone_black.xml`` without any change. That is what we want, no?

**Comment by flixr** [comment]
But I want to be able to just compile/test an airframe file from the untested dir without having to do any changes or moving it to examples first.
So that is why I propose to have a flat tree, with no more subdirs under examples or untested...

**Comment by podhrmic** [comment]
OK. Do you want all files in one folder (i.e. no subdirs in ``untested``) or have 

untested
untested-> examples
untested-> TestHardware

?

**Comment by flixr** [comment]
As I said I would vote for a flat tree, so no subfolders...
And you can delete the empty airframes from TestHardware...

**Comment by podhrmic** [comment]
This should do it...

**Pull request closed without merging**
