### PR TITLE
Dual video thread

### PR DESCRIPTION
**Pull request by dewagter**
anyone a better idea? [and don't say: c++ ]

### CODE REVIEW

**Comment by flixr** [comment]
Make `video_thread` and array... and initialize/handle all threads in the same module...

Care has to be take for some functions that access shared resources though, e.g. `video_thread_save_shot` shouldn't try to open/save the same files in both threads.
That can also go wrong in the state of this PR with a basically duplicated video_thread2 module...

**Comment by rmeertens** [comment]
Extend the struct video_config_t ? To include a linked list with functions to call after each image?
What do you think about this idea?

**Comment by rmeertens** [comment]
Also a suggestion: extend video_config_t with the parameters of the camera (FOV_W,FX, etc). What do you think about it?

**Comment by dewagter** [comment]
makes sense to me

-Christophe

**Comment by wilcoschoneveld** [comment]
I guess it would make sense to close this pull request?

**Pull request closed without merging**
