### PR TITLE
only run adaptive throttle estimation if desired zd was updated

### LINKED ISSUE #1857: Adapted Throttle causes drop in guidance height
Hi, I have an issue with the vertical guidance with ADAPT_THROTTLE_ENABLED on true. 

If I switch from AP_MODE_ATTITUDE_RC_CLIMB to AP_MODE_HOVER_Z_HOLD with the Bebop 1 at 1-2 meters, it drops to the ground and slowly rises to the correct height. However I want it to stay at that height from the beginning 

I had the same problem with AP_MODE_ATTITUDE_DIRECT  to hover, but that is because it didn't adapt the intergral factor by the adapt throttle. However, with RC_CLIMB, it is already using the adapt_throttle in guidance... 

Anybody have any thoughts on how to fix this? Thanks in advance.

### PR DESCRIPTION
**Pull request by flixr**
Only run adaptive throttle estimation if we are in flight and
the desired vertical velocity (zd) was updated (i.e. we ran hover_loop before).
This means that the estimation is not updated when using direct throttle commands.

This should fix #1857

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
The nice thing about running adaptation in manual throttle is that it was easier to see if it works and if the convergence rate of the filter is correct. Should we add (yet another) flag to enable it in manual for debugging ?

**Comment by flixr** [comment]
I don't see how it could ever properly work in manual mode... since you pass the "desired" vertical velocity to `gv_adapt_run`, but this is not set (and can't be known) in manual mode. It just has the last value or zero, but that will cause a wrong adaption if you are actually not trying to hover...

**Comment by gautierhattenberger** [comment]
That was the idea, hover in manual to check that estimation is not doing something stupid before switching to altitude control where estimation and actual control are interacting each other. But it is not a big deal, you can merge like this if you want.

**Comment by flixr** [comment]
> That was the idea, hover in manual to check that estimation is not doing something stupid

But if you don't hover and instead really fly around, it definitely will do something stupid, namely not properly estimate your hover throttle...

**Pull request merged**
