### PR TITLE
Opticflow plugs into video thread

### PR DESCRIPTION
**Pull request by dewagter**
no need to redefine the video thread

this should become an example for video processing stuff:

 - plug into one of the video_threads
 - thread safe data copy to paparazzi
 - publish ABI

### CODE REVIEW

**Comment by flixr** [comment]
One of the video_threads?

**Comment by dewagter** [comment]
good point: this means currently we can have opticflow bottom camera and other-computervision on the front via video_thread. After this pull request that is not possible anymore!?

Maybe first need the multi_video_thread....

**Comment by flixr** [comment]
That is correct.

**Comment by dewagter** [comment]
outdated

**Comment by flixr** [comment]
Why is this outdated? I still think it is a good idea, we just need to support two threads in the video_thread module first...

**Comment by flixr** [comment]
@dewagter do you already have updates for stuff like this? Running multiple video threads... running opticflow on different cams?

**Comment by dewagter** [comment]
@flixr I do not have a multi-thread update yet

**Comment by flixr** [comment]
Just wondering why you closed this...

**Pull request closed without merging**
