### PR TITLE
Refactor xsens

### PR DESCRIPTION
**Pull request by flixr**
Might still be missing some stuff and is untested...

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
I don't have working XSens either, but it looks much better like this. Can someone test it ?
Otherwise I still suggest to merge, it makes the code cleaner.

**Comment by dewagter** [comment]
For Delft you can merge the new xsens code.

-Christophe

**Comment by podhrmic** [comment]
If nobody has means to test it, shouldn't we just remove the code or at least mark is as obsolete?

**Comment by flixr** [comment]
I thought that @dewagter and co. have an xsens in one of their planes...

**Comment by dewagter** [comment]
We do have 2 xsens planes. For now they fly with older code. We need to
upgrade them with new paparazzi. We do have the means to test it, just not
this week as I'm not in Delft.

-Christophe

**Comment by flixr** [comment]
I would wait with merging until it has been tested as the handling of GPS position/vel is different now and I'm not sure exactly which information is meant to be used for the INS and which for the "raw" GPS part...

Also still TODO:
* fix ins_xsens modules or directly convert the subsystems to modules
* multi GPS support?

**Comment by flixr** [comment]
The different signs (IMU/sensor orientation) between the different xsens types is also weird and unclear.
See also related #924

**Comment by flixr** [comment]
@dewagter any chance someone in your Lab can try this soon-ish?

**Comment by flixr** [comment]
Also converted the xsens subsystems to modules...
I would like to merge this ASAP so we can get on with things.

This still really needs to be tested with a real XSens though... also the `XSENS_OUTPUT_MODE` might not be correct for all cases...

**Pull request merged**
