### PR TITLE
Update Piksi driver

### PR DESCRIPTION
**Pull request by flixr**
Improved version of #1271 with additionally (split up the commits from @fvantienen on his piksi branch):
- add DGPS and RTK fix modes to GPS
- fix uart write on linux
- add GPS_INJECT message
- add sbp2ivy

### CODE REVIEW

**Comment by fvantienen** [comment]
Good to merge for me :)

**Comment by simmis** [comment]
@fvantienen, was that merged with all required commits included? I am seeing compilation errors when I `make clean && make`: 
        firmwares/rotorcraft/datalink.c: In function 'dl_parse_msg':
    firmwares/rotorcraft/datalink.c:169:10: error: 'DL_GPS_INJECT' undeclared (first use in this function)
         case DL_GPS_INJECT :

Or did I miss to update some other configuration?

**Comment by flixr** [comment]
@simmis did you really do a `make clean && make`?
`DL_GPS_INJECT` should be generated with make from the added `GPS_INJECT` datalink message.

**Comment by simmis** [comment]
@flixr, yes I used the "clean" and "make" buttons. 

I just also tried to `make` in the paparazzi root directory. But now I got another error (sth. with luftboot.c) that I need to investigate tomorrow...

**Comment by flixr** [comment]
@simmis you need to run make in the paparazzi root dir in order to update the generated code for messages and the ground segment...
The clean and make button in the Paparazzi Center only recompile the aircraft firmware...

**Comment by simmis** [comment]
@flixr, ok, thanks. Got it. Will take a look into the other error tomorrow. Probably also sth. trivial.

**Pull request merged**
