### PR TITLE
[gps] add fields_valid and remove GPS_USE_LATLONG

### LINKED ISSUE #641: GPS cleanup and better LTP origin handling (UTM vs. NED)
- add flags/bitfield to the global GpsState struct to indicate which representations are actually provided by the gps driver
- no need to always calculate UTM pos in GPS drives with GPS_USE_LATLONG, should be handled by the state interface (especially considering that only the old ublox provide position in UTM directly)
- less direct dependencies on GPS (e.g. in common_nav)

  e.g. nav_reset_reference should probably just read the current position from the state interface and reset the reference according to that, instead of explicitly using lla or utm from gps to call stateSetLocalUtmOrigin_f.

This probably also means that in the state interface the ltp_def (origin of local frame) should be set in stateSetLocalUtmOrigin_f as well (and vice versa)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9299807-gps-cleanup-and-better-ltp-origin-handling-utm-vs-ned?utm_campaign=plugin&utm_content=tracker%2F10895&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10895&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by flixr**
add fields_valid bitfiled to gps struct and use that to decide whether a valid UTM pos is availabe instead of always computing UTM if GPS_USE_LATLONG is defined

should close #641

### CODE REVIEW

**Comment by kirkscheper** [comment]
Loving this Felix!

**Comment by flixr** [comment]
Tests to confirm all is still working as expected would be appreciated, I could only test the sim...
@gautierhattenberger do you think we should wait with this for after the v5.8 release?

**Comment by gautierhattenberger** [comment]
This is a really nice change, but except testing some ublox module in the lab, I won't be able to do more before leaving for vacations. It doesn't really change much for end-users and it may have some side effects if we missed some stupid bugs, so maybe it is not wise for a stable release...

**Comment by flixr** [comment]
Agreed, waiting for after the release...

**Pull request merged**
