### PR TITLE
Same message in FULL INDI and INDI Simple

### PR DESCRIPTION
**Pull request by dewagter**
- [x] https://github.com/paparazzi/pprzlink/pull/177

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
Looks good. Waiting for corrections, merging and ref update for pprzlink.

**Comment by EwoudSmeur** [comment]
Thanks for these efforts, great improvement!

Actually, now that I'm thinking about it, maybe we can take this one step further, and fully merge the files. INDI simple is a special case of full INDI with an identity control effectiveness matrix, if we send the output to the motor mixing via the stabilization commands. I'm fine with merging this and making the other change later.

**Review by EwoudSmeur — APPROVED** [review]
See my previous comment

**Comment by dewagter** [comment]
```make test``` all OK

**Pull request merged**
