### PR TITLE
Actuators in PPRZ values

### PR DESCRIPTION
**Pull request by dewagter**
We would like to have PPRZ units in telemetry and logs. @gautierhattenberger @fvantienen @Fabien-B 
 - a) can this be the default?  
 - b) should we make a define to select this
 - c) should I make 2 messages: driver-value and PPRZ value

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
Since it is a downlink message, you can send several variable length arrays (only parsing from C code is not working), an other option is:
- d) send driver and pprz values in ACTUATORS message

**Comment by dewagter** [comment]
Implemented d)

**Comment by dewagter** [comment]
Using https://github.com/paparazzi/pprzlink/pull/187

**Comment by dewagter** [comment]
@fvantienen @gautierhattenberger Now implemented option C.
 - uses less telemetry / log space. I added slow MESSAGES_RAW by default.
 - you can still trim: look at the RAW message just like when checking RAW sensor data.
 - highspeed logs are in unified PPRZ units.

**Review by gautierhattenberger — APPROVED** [review]

**Pull request merged**
