### PR TITLE
Cleanup cdw airframes

### PR DESCRIPTION
**Pull request by dewagter**

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
beside mixing several stuff (cleaning conf, chimu fix) it looks good to me.

**Comment by dewagter** [comment]
Is there a way to trigger a full reintegration server test of all conf
files?

-Christophe

**Comment by flixr** [comment]
Unfortunately neither travis nor semaphore offers something like that, testing all confs is done daily with the semaphore scheduler (but that can only be enabled for one branch, in our case master).

You can run them all locally with `make test_all_confs` though...

**Comment by dewagter** [comment]
I tested all confs locally and they all compile. This can be merged/squashed/reintegrated in the preferred way.

**Comment by flixr** [comment]
ups, that was one click too much... actually wanted to select merge instead of squash...

**Pull request merged**
