### PR TITLE
fix and update mavlink

### PR DESCRIPTION
**Pull request by Fabien-B**
Replace `python2` by `python` as python2 is deprecated, and it make paparazzi build fail on Ubuntu 22.04.

Also take this opportunity to update mavlink, and link to the original repository as the changes in the paparazzi fork are included upstream.

This PR needs testing, can someone using mavlink test it ?

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
It seems that there is a dependency issue with the `future` module from python

**Comment by Fabien-B** [comment]
Then I propose to remove mavlink from the `all` Makefile target.
It is still possible to use it if you care to install the `future` module.

**Comment by fvantienen** [comment]
Somehow it still got build in semaphore?

**Comment by gautierhattenberger** [comment]
problem is coming from here: https://github.com/paparazzi/paparazzi/blob/master/Makefile#L109

**Comment by Fabien-B** [comment]
Now it should work, when the docker image will be updated.

**Review by gautierhattenberger — APPROVED** [review]

**Pull request merged**
