### PR TITLE
[ahrs] check if all AHRS are aligned

### PR DESCRIPTION
**Pull request by dewagter**
needed in several automatic flightplans
to be used in arming

but: is this the way to go?

### CODE REVIEW

**Comment by flixr** [comment]
Not quite sure if this is the way to go either...

Using this in a flight plan only works if you have an AHRS, so e.g. not for a full INS where you don't need an AHRS... (e.g. vectornav, xsens...)

To just check if the actually used atiitude estimate is valid (the primary AHRS is aligned) it is easier to simply use `stateIsAttitudeValid()`, which will also work for the pure/full INS solutions....

**Comment by dewagter** [comment]
Yes we plan to use dual-imu more and more: e.g. external IMU + aspirin backup. Why did you make it otherwise ;-)

But if you really don't want this code in master, I can understand and you can throw it away, but ideally we should cherry-pick the output-enable for CHIMU.

**Comment by flixr** [comment]
> Yes we plan to use dual-imu more and more: e.g. external IMU + aspirin backup. Why did you make it otherwise ;-)

Me too, but was just wondering if you _already_ use it regularly... since there are still some annoyances (#1145)

> But if you really don't want this code in master, I can understand and you can throw it away, but ideally we should cherry-pick the output-enable for CHIMU.

Well, I was still hoping that someone comes up with a nicer solution on how to register/enable/check multiple AHRS implementations in a way that also harmonizes with full INS solutions that don't have any separate AHRS functions.

Also the name is_aligned is maybe a bit too specific and doesn't exactly apply to all, what we actually want to know if the AHRSs are *ready*.
And we really want to know that not only for the AHRS, but also other subsystems/sensors.
I think for this we should start looking at how to check if all required systems are ready in a more generic way...

That is why I was asking if you are already using multiple AHRS *now* and you really need something like in this PR... if yes we can merge it for lack of something better right now. But in the longer run I don't think this is the way to go.

**Comment by dewagter** [comment]
Yes, every subsystem should add itself to the generic Ready-list. And at
the same time critical things should also have a watchdog.

**Comment by dewagter** [comment]
I saw you added the the CHIMU enable. So shall we delete this code or do you want to use it as base?

**Comment by flixr** [comment]
Let's keep it open for now, maybe we still need it before we can come up with a better solution...

**Pull request closed without merging**
