### PR TITLE
Update libopencm3 and add Random Number Generator (RNG)

### PR DESCRIPTION
**Pull request by podhrmic**
RNG is a prerequisite for secure pprzlink.
Updated libopencm3 already has drivers for RNG.
ChibiOS would have to be updated too, but the new ChibiOS currently doesn't work with [TLS module](https://github.com/paparazzi/paparazzi/blob/master/conf/modules/tlsf.xml)
LPC21 autopilots don't have the RNG hardware.

Tested on Lisa MX. Most stm32 chips have RNG hardware.

@gautierhattenberger any chance you would want to update TLS to work with the new Chibios?

### CODE REVIEW

**Comment by podhrmic** [comment]
The errors are due to #2194 - not because of changes introduced here.

**Comment by podhrmic** [comment]
@gautierhattenberger any comments on this or can I merge?

**Comment by kirkscheper** [comment]
It looks like the commit history is a bit mixed up, your changes seemed to be mixed in with ones that are already upstream. Can you rebase your changes on top of the current master?

**Comment by gautierhattenberger** [comment]
beside the rebase issue, it looks fine

**Pull request merged**
