### PR TITLE
Ap mode setting

### PR DESCRIPTION
**Pull request by gautierhattenberger**
Allow to change some modes from settings even without RC for rotorcraft firmware.

This solution have been discussed in #1819

### CODE REVIEW

**Comment by flixr** [comment]
Functionality wise it looks good to me, just wondering if we can't find a better name for the settings handler... having a CamelCase version (while the one without rc check is snake_case) can be a bit confusing....

**Comment by gautierhattenberger** [comment]
`autopilot_SetModeHandler` ?

**Comment by flixr** [comment]
Yeah, I think that would more clear than simply `autopilot_SetMode`...
`autopilot_SetModeRcCheck` or something like that isn't really better than `autopilot_SetModeHandler` either....

**Comment by gautierhattenberger** [comment]
Can I merge this one ?

**Pull request merged**
